import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Navbar } from './components/Navbar';
import { Footer } from './components/Footer';
import { SearchView } from './components/SearchView';
import { ServiceBrowser } from './components/ServiceBrowser';
import { ServiceDetail } from './components/ServiceDetail';
import { BookingSummaryStep } from './components/BookingSummaryStep';
import { SelectDetailsStep } from './components/SelectDetailsStep';
import { PiPaymentModal } from './components/PiPaymentModal';
import { BookingStatusView } from './components/BookingStatusView';
import { ProviderDashboardView } from './components/ProviderDashboardView';
import { PublicProfileView } from './components/PublicProfileView';
import { ChatView } from './components/ChatView';
import { UserProfileView } from './components/UserProfileView';
import { BecomeProviderStep } from './components/BecomeProviderStep';
import { BecomeProviderModal } from './components/BecomeProviderModal';
import { ProviderServicesView } from './components/ProviderServicesView';
import { FeedbackWidget } from './components/FeedbackWidget';
import { PullToRefreshIndicator } from './components/PullToRefreshIndicator';
import { serviceService } from './services/serviceService';
import { providerService } from './services/providerService';
import { bookingService } from './services/bookingService';
import { businessService } from './services/businessService';
import { piAuthService } from './services/piAuthService';
import { supabase } from './lib/supabase';
import { Service, Provider, BusinessProfile, Booking, PiUser } from './types';
import './index.css';

const App: React.FC = () => {
  const [services, setServices] = useState<Service[]>([]);
  const [business, setBusiness] = useState<BusinessProfile | null>(null);
  const [bookings, setBookings] = useState<Booking[]>([]);
  const [piUser, setPiUser] = useState<PiUser | null>(null);
  const [activeTab, setActiveTab] = useState<'browse' | 'search' | 'bookings' | 'chat'>('browse');
  const [currentFlow, setCurrentFlow] = useState<string>('browse');
  const [selectedService, setSelectedService] = useState<Service | null>(null);
  const [selectedProfile, setSelectedProfile] = useState<BusinessProfile | Provider | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [clientDetails, setClientDetails] = useState<any>({ clientName: '', clientPiUsername: '', clientPhone: '', clientEmail: '', notes: '' });
  const [myProviderId, setMyProviderId] = useState<string | null>(null);
  const [loadingBusiness, setLoadingBusiness] = useState(true);
  const [isPulling, setIsPulling] = useState(false);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [pullDistance, setPullDistance] = useState(0);
  const [pullProgress, setPullProgress] = useState(0);
  const [isThresholdReached, setIsThresholdReached] = useState(false);
  const [isSubmittingProvider, setIsSubmittingProvider] = useState(false);
  const [showBecomeProviderModal, setShowBecomeProviderModal] = useState(false);
  const refreshProfile = useCallback(async () => { if (!piUser) return; try { const profile = await piAuthService.getUserProfileAsync(piUser.uid); if (profile) setPiUser((current) => current ? { ...current, ...profile } : current); } catch (error) { console.warn('Failed to refresh profile:', error); } }, [piUser]);
  const refreshBookings = useCallback(async () => { try { const loaded = await bookingService.getBookingsAsync(); setBookings(loaded); } catch (error) { console.warn('Failed to refresh bookings:', error); } }, []);
  useEffect(() => { refreshBookings(); }, [refreshBookings, piUser?.uid]);
  useEffect(() => { if (piUser?.uid) refreshBookings(); }, [piUser?.uid, refreshBookings]);
  const clientBookings = useMemo(() => { if (!piUser) return []; const uid = String(piUser.uid || '').trim(); const username = String(piUser.username || '').trim().replace(/^@+/, '').toLowerCase(); return bookings.filter((b) => { const bookingUid = String(b.clientPiUid || '').trim(); if (uid && bookingUid) return bookingUid === uid; const bookingUsername = normalizePiUsername(b.clientPiUsername); return !!username && bookingUsername === username; }); }, [bookings, piUser]);
  const handleCancelBooking = async (bookingId: string) => { await bookingService.updateBookingStatusAsync(bookingId, 'Cancelled'); await refreshBookings(); };
  const handleConfirmCompletion = async (bookingId: string) => { await bookingService.updateBookingEscrowStatusAsync(bookingId, 'completion_confirmed'); await refreshBookings(); };
  const handleAcceptBooking = async (bookingId: string) => { await bookingService.updateBookingStatusAsync(bookingId, 'In Progress'); await refreshBookings(); };
  const handleRejectBooking = async (bookingId: string, reason: string, payoutTxHash?: string) => { await bookingService.updateBookingStatusAsync(bookingId, 'Cancelled', reason, payoutTxHash); await refreshBookings(); };
  const handleNavigateHome = () => { setActiveTab('browse'); setCurrentFlow('browse'); };
  const handleNavigateSearch = () => { setActiveTab('search'); };
  const handleNavigateBookings = () => { setActiveTab('bookings'); setCurrentFlow('status'); };
  const handleNavigateChat = () => { setActiveTab('chat'); };
  const handleOpenBookingChat = (bookingId: string) => { sessionStorage.setItem('w3c_open_chat_booking', bookingId); setActiveTab('chat'); setCurrentFlow('browse'); };
  const handleOpenAboutBusiness = () => { setActiveTab('browse'); setSelectedProfile(businessWithServices); setCurrentFlow('about'); };
  const handleOpenProviderProfile = async (provider: Provider) => { setActiveTab('browse'); try { const providers = await providerService.getProvidersAsync(); const completeProvider = providers.find((item) => item.id === provider.id) || provider; setSelectedProfile(completeProvider); } catch { setSelectedProfile(provider); } setCurrentFlow('about'); };
  const businessWithServices = { ...business, services }; if (loadingBusiness && !business) return null;
  return <div className="min-h-screen w-full flex flex-col bg-white text-zinc-900 font-sans selection:bg-amber-500 selection:text-white transition-colors overflow-x-hidden"><PullToRefreshIndicator isPulling={isPulling} isRefreshing={isRefreshing} pullDistance={pullDistance} pullProgress={pullProgress} isThresholdReached={isThresholdReached} /><Navbar currentBusiness={businessWithServices} piUser={piUser} piAuthLoading={false} onSignIn={() => {}} onSignOut={() => {}} hasProvider={!!myProviderId} onOpenBecomeProvider={() => {}} onOpenProviderConsole={() => { setActiveTab('browse'); setCurrentFlow('provider_console'); }} onOpenProviderServices={() => {}} onOpenProfile={() => {}} activeTab={activeTab} currentFlow={currentFlow} bookingsCount={clientBookings.filter((b) => b.status === 'Confirmed' || b.status === 'Pending' || b.status === 'In Progress').length} onNavigateHome={handleNavigateHome} onNavigateSearch={handleNavigateSearch} onNavigateBookings={handleNavigateBookings} onNavigateChat={handleNavigateChat} onOpenAboutBusiness={handleOpenAboutBusiness} /><FeedbackWidget /><main className="w-full max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-6 flex-1">{activeTab === 'search' ? <SearchView services={services} onSelectService={() => {}} onSelectProvider={handleOpenProviderProfile} onBecomeProvider={() => {}} initialQuery={searchQuery} /> : activeTab === 'chat' ? <ChatView onNavigateHome={handleNavigateHome} /> : activeTab === 'browse' ? currentFlow === 'profile' && piUser ? <UserProfileView piUser={piUser} onBack={handleNavigateHome} onProfileUpdated={refreshProfile} /> : currentFlow === 'browse' ? <ServiceBrowser business={businessWithServices} services={services} onSelectService={() => {}} onOpenAbout={(merchant) => { setSelectedProfile(merchant || null); setCurrentFlow('about'); }} onOpenSearch={() => setActiveTab('search')} /> : currentFlow === 'about' ? <PublicProfileView merchant={selectedProfile || businessWithServices} services={services} onBack={() => setCurrentFlow('browse')} onSelectService={() => {}} /> : currentFlow === 'detail' && selectedService ? <ServiceDetail service={selectedService} business={businessWithServices} onBack={() => setCurrentFlow('browse')} onProceedToBooking={() => setCurrentFlow('select_details')} onOpenProviderProfile={handleOpenProviderProfile} /> : currentFlow === 'select_details' && selectedService ? <SelectDetailsStep service={selectedService} initialDetails={clientDetails} onBack={() => setCurrentFlow('detail')} onProceedToSummary={setClientDetails} /> : currentFlow === 'review_summary' && selectedService ? <BookingSummaryStep service={selectedService} business={businessWithServices} clientDetails={clientDetails} piUser={piUser} onBack={() => setCurrentFlow('select_details')} onProceedToPayment={() => setCurrentFlow('payment')} /> : currentFlow === 'become_provider' ? null : currentFlow === 'provider_console' ? <ProviderDashboardView piUser={piUser} providerId={myProviderId || ''} bookings={bookings} onBack={() => setCurrentFlow('browse')} onAcceptBooking={handleAcceptBooking} onRejectBooking={handleRejectBooking} onProviderUpdated={refreshBookings} onOpenBookingChat={handleOpenBookingChat} /> : currentFlow === 'provider_services' ? <ProviderServicesView onBack={() => setCurrentFlow('browse')} /> : <ServiceBrowser business={businessWithServices} services={services} onSelectService={() => {}} onOpenAbout={() => {}} onOpenSearch={() => setActiveTab('search')} /> : <BookingStatusView bookings={clientBookings} onBrowseServices={() => { setActiveTab('browse'); setCurrentFlow('browse'); }} onCancelBooking={handleCancelBooking} onAddReview={bookingService.submitBookingReviewAsync} onConfirmCompletion={handleConfirmCompletion} onOpenChat={handleOpenBookingChat} /></main></div>;
}

function normalizePiUsername(username?: string | null): string { return String(username || '').trim().replace(/^@+/, '').toLowerCase(); }

export default App;