import { addBookingSystemMessage } from "../routes/pi-chat";

/** Server-side App-to-User (A2U) client refund. */
export type RefundResult = { status: "completed" | "failed" | "recovered" | "skipped"; paymentId?: string; txid?: string; error?: string; bookingId?: string };
async function createPiClient(apiKey: string, walletPrivateSeed: string) { const mod: any = await import("pi-backend"); let PiNetworkClass = mod?.default ?? mod; if (PiNetworkClass && typeof PiNetworkClass !== "function" && typeof PiNetworkClass.default === "function") PiNetworkClass = PiNetworkClass.default; if (typeof PiNetworkClass !== "function") throw new Error("pi-backend PiNetwork constructor is not available (import interop failure)."); return new PiNetworkClass(apiKey, walletPrivateSeed); }
function config() { const url = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL; const key = process.env.SUPABASE_SECRET_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY; return url && key ? { url: url.replace(/\/$/, ""), key } : null; }
async function sb(path: string, init: RequestInit = {}) { const c = config(); if (!c) return null; const h = new Headers(init.headers); h.set("apikey", c.key); h.set("Content-Type", "application/json"); h.set("Prefer", h.get("Prefer") || "return=representation"); if (c.key.startsWith("eyJ")) h.set("Authorization", `Bearer ${c.key}`); return fetch(`${c.url}/rest/v1/${path}`, { ...init, headers: h }); }
function refundableEscrow(status: string | undefined | null) { return status === "paid_escrowed" || status === "refund_processing" || status === "refund_failed"; }
export async function executeAutomaticClientRefund(bookingId: string, opts?: { reason?: string; cancelBooking?: boolean; cancellationMessage?: string }): Promise<RefundResult> {
  const reason = opts?.reason?.trim() || "Escrow refund"; const cancelBooking = opts?.cancelBooking !== false; const cancellationMessage = opts?.cancellationMessage?.trim() || `Booking #${bookingId} was cancelled. Reason: ${reason}`;
  if (!config()) return { status: "failed", bookingId, error: "Supabase server credentials are missing." };
  const bres = await sb(`bookings?id=eq.${encodeURIComponent(bookingId)}&select=id,status,escrow_status,price_pi,client_pi_uid,refund_pi_payment_id,refund_pi_txid&limit=1`);
  if (!bres?.ok) { const detail = bres ? await bres.text().catch(() => "") : ""; return { status: "failed", bookingId, error: `Booking lookup failed${bres ? ` (${bres.status})` : ""}${detail ? `: ${detail.slice(0, 300)}` : ""}.` }; }
  const bookingRows = await bres.json() as any[]; const booking = Array.isArray(bookingRows) ? bookingRows[0] : null; if (!booking) return { status: "failed", bookingId, error: "Booking not found." };
  if (booking.escrow_status === "refunded") return { status: "recovered", bookingId, paymentId: booking.refund_pi_payment_id || undefined, txid: booking.refund_pi_txid || undefined };
  if (booking.escrow_status === "released" || booking.status === "Completed") return { status: "skipped", bookingId, error: "Booking escrow was already released to the provider; refund is not allowed." };
  if (!refundableEscrow(booking.escrow_status)) return { status: "failed", bookingId, error: `Booking escrow_status=${booking.escrow_status || "null"} is not eligible for refund.` };
  const clientUid = String(booking.client_pi_uid || "").trim().replace(/^@/, ""); if (!clientUid) return { status: "failed", bookingId, error: "Booking is missing client_pi_uid; cannot route A2U refund." };
  const amount = Number(booking.price_pi); if (!Number.isFinite(amount) || amount <= 0) return { status: "failed", bookingId, error: "Booking price_pi is invalid; cannot refund." };
  const now = new Date().toISOString();
  if (booking.escrow_status === "paid_escrowed") { const claim = await sb(`bookings?id=eq.${encodeURIComponent(bookingId)}&escrow_status=eq.paid_escrowed`, { method: "PATCH", body: JSON.stringify({ escrow_status: "refund_processing", updated_at: now, acceptance_deadline: null }) }); if (!claim?.ok) { const detail = claim ? await claim.text().catch(() => "") : ""; return { status: "failed", bookingId, error: `Failed to claim booking for refund (${claim?.status})${detail ? `: ${detail.slice(0, 300)}` : ""}.` }; } const claimed = (await claim.json() as any[]) || []; if (!claimed.length) { const reread = await sb(`bookings?id=eq.${encodeURIComponent(bookingId)}&select=escrow_status&limit=1`); const row = reread?.ok ? (await reread.json() as any[])[0] : null; if (row?.escrow_status === "refunded") return { status: "recovered", bookingId }; if (row?.escrow_status !== "refund_processing") return { status: "failed", bookingId, error: "Could not claim booking for refund (concurrent update)." }; } }
  else if (booking.escrow_status === "refund_failed" || booking.escrow_status === "refund_processing") await sb(`bookings?id=eq.${encodeURIComponent(bookingId)}`, { method: "PATCH", body: JSON.stringify({ escrow_status: "refund_processing", acceptance_deadline: null, updated_at: now }) }).catch(() => undefined);
  const apiKey = process.env.PI_API_KEY?.trim(); const seed = (process.env.PI_WALLET_PRIVATE_SEED || process.env.PI_PRIVATE_SEED || "").trim(); if (!apiKey) { await markRefundFailed(bookingId, "PI_API_KEY is missing."); return { status: "failed", bookingId, error: "PI_API_KEY is missing." }; } if (!seed) { await markRefundFailed(bookingId, "Pi app wallet private seed is missing."); return { status: "failed", bookingId, error: "Pi app wallet private seed (PI_WALLET_PRIVATE_SEED) is missing." }; }
  let paymentId = ""; let txid = "";
  try {
    const pi = await createPiClient(apiKey, seed); const created: any = await pi.createPayment({ amount, memo: `Refund for booking ${bookingId}`.slice(0, 25), metadata: { bookingId, type: "client_refund", reason }, uid: clientUid }); paymentId = String(typeof created === "string" ? created : (created?.identifier || created?.id || "")); if (!paymentId) { await markRefundFailed(bookingId, "Pi did not return a refund payment identifier.", paymentId, txid); return { status: "failed", bookingId, error: "Pi did not return a refund payment identifier." }; }
    const submitted = await pi.submitPayment(paymentId); txid = typeof submitted === "string" ? submitted : String((submitted as any)?.txid || (submitted as any)?.transaction?.txid || ""); if (!txid) { await markRefundFailed(bookingId, "Pi did not return a refund transaction ID.", paymentId, txid); return { status: "failed", bookingId, paymentId, error: "Pi did not return a refund transaction ID." }; }
    await pi.completePayment(paymentId, txid);
    const finalizedAt = new Date().toISOString(); const finalize = await sb(`bookings?id=eq.${encodeURIComponent(bookingId)}&escrow_status=eq.refund_processing`, { method: "PATCH", body: JSON.stringify({ escrow_status: "refunded", payment_status: "Refunded", refunded_at: finalizedAt, updated_at: finalizedAt, refund_pi_payment_id: paymentId, refund_pi_txid: txid, refund_reason: reason, acceptance_deadline: null, ...(cancelBooking ? { status: "Cancelled", cancelled_at: finalizedAt, rejection_reason: reason } : {}) }) });
    if (!finalize?.ok) { const detail = finalize ? await finalize.text().catch(() => "") : ""; return { status: "failed", bookingId, paymentId, txid, error: `Pi A2U refund succeeded on-chain, but booking could not be marked refunded (${finalize?.status})${detail ? `: ${detail.slice(0, 300)}` : ""}. Manual reconciliation required.` }; }
    const finalized = (await finalize.json() as any[]) || [];
    if (!finalized.length) { const check = await sb(`bookings?id=eq.${encodeURIComponent(bookingId)}&select=escrow_status,refund_pi_payment_id,refund_pi_txid&limit=1`); const row = check?.ok ? (await check.json() as any[])[0] : null; if (row?.escrow_status === "refunded") { if (cancelBooking) try { await addBookingSystemMessage(bookingId, cancellationMessage); } catch {} return { status: "recovered", bookingId, paymentId: row.refund_pi_payment_id || paymentId, txid: row.refund_pi_txid || txid }; } return { status: "failed", bookingId, paymentId, txid, error: "Pi A2U refund succeeded, but concurrent state update prevented marking refunded." }; }
    if (cancelBooking) { try { await addBookingSystemMessage(bookingId, cancellationMessage); } catch {} }
    return { status: "completed", bookingId, paymentId, txid };
  } catch (e: any) { const msg = e?.message || "Automatic Pi A2U refund failed."; await markRefundFailed(bookingId, msg, paymentId, txid); return { status: "failed", bookingId, paymentId: paymentId || undefined, txid: txid || undefined, error: msg }; }
}
async function markRefundFailed(bookingId: string, error: string, paymentId?: string, txid?: string) { const now = new Date().toISOString(); await sb(`bookings?id=eq.${encodeURIComponent(bookingId)}`, { method: "PATCH", body: JSON.stringify({ escrow_status: "refund_failed", updated_at: now, rejection_reason: `Refund failed: ${error}`.slice(0, 500), ...(paymentId ? { refund_pi_payment_id: paymentId } : {}), ...(txid ? { refund_pi_txid: txid } : {}) }) }).catch(() => undefined); }
