import { Router, type IRouter } from "express";
import healthRouter from "./health";
import piAuthRouter from "./pi-auth";
import piPaymentsRouter from "./pi-payments";
import piPayoutsRouter from "./pi-payouts";
import piBookingsRouter from "./pi-bookings";
import piStage6Router from "./pi-stage6";
import piDeliveryRouter from "./pi-delivery";
import piServicesRouter from "./pi-services";
import piChatRouter from "./pi-chat";
import piChatMarketplaceRouter from "./pi-chat-marketplace";
import feedbackRouter from "./feedback";
import piPricingRouter from "./pi-pricing";
import userProfileRouter from "./user-profile";
const router: IRouter = Router();
router.use(healthRouter);
router.use(piAuthRouter);
router.use(piPaymentsRouter);
router.use(piPayoutsRouter);
router.use(piStage6Router);
router.use(piBookingsRouter);
router.use(piDeliveryRouter);
router.use(piServicesRouter);
router.use(piPricingRouter);
router.use(piChatRouter);
router.use(piChatMarketplaceRouter);
router.use(feedbackRouter);
router.use(userProfileRouter);
export default router;
