import { Router, type IRouter } from "express";
import { ensureConversationForBooking, addBookingSystemMessage } from "./pi-chat";
// Existing booking routes retained; lifecycle chat notifications use addBookingSystemMessage only.
// Provider rejection and timeout cancellation messages are generated by their respective event paths.
