import { Router, type IRouter } from "express";
import { quoteFiatToPi } from "../services/piPricingService";

const router: IRouter = Router();
function getSupabaseConfig() { const url = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL; const key = process.env.SUPABASE_SECRET_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY; return url && key ? { url: url.replace(/\/$/, ""), key } : null; }
async function supabaseRequest(path: string, init: RequestInit = {}) { const config = getSupabaseConfig(); if (!config) return null; const headers = new Headers(init.headers); headers.set("apikey", config.key); headers.set("Content-Type", "application/json"); headers.set("Prefer", headers.get("Prefer") || "return=representation"); if (config.key.startsWith("eyJ")) headers.set("Authorization", `Bearer ${config.key}`); return fetch(`${config.url}/rest/v1/${path}`, { ...init, headers }); }
async function verifyPiAccessToken(accessToken: string) { const response = await fetch("https://api.minepi.com/v2/me", { headers: { Authorization: `Bearer ${accessToken.trim()}` } }); if (!response.ok) return null; const user = await response.json() as { uid?: string; username?: string }; return user.uid ? user : null; }
async function getProviderByPiUid(piUid: string) { const response = await supabaseRequest(`providers?select=id,pi_uid,full_name,role_title,status&pi_uid=eq.${encodeURIComponent(piUid)}&limit=1`); if (!response) return null; if (!response.ok) throw new Error(`Supabase provider lookup failed (${response.status}).`); const rows = await response.json() as any[]; return rows[0] || null; }
const DURATION_LIMITS: Record<string, number> = { minutes: 59, hours: 24, days: 30, weeks: 4, months: 12 };
const DURATION_MULTIPLIERS: Record<string, number> = { minutes: 1, hours: 60, days: 1440, weeks: 10080, months: 43200 };
const LEGACY_CATEGORY_MAP: Record<string, string> = { web_dev: 'web-software-development', web_development: 'web-software-development', 'web development': 'web-software-development', landing_page: 'web-software-development', ux_design: 'ui-ux-product-design', pi_sdk: 'blockchain-web3-development', consulting: 'project-professional-services', graphics_design: 'graphic-visual-design', graphic_design: 'graphic-visual-design', graphics: 'graphic-visual-design' };
async function resolveCategoryId(categoryId: unknown, legacyCategory: unknown) {
  const rawId = String(categoryId || '').trim(); const legacy = String(legacyCategory || '').trim().toLowerCase(); const slug = rawId || LEGACY_CATEGORY_MAP[legacy] || '';
  if (!slug) throw new Error('A marketplace category is required.');
  const filter = /^[0-9a-f-]{36}$/i.test(slug) ? `id=eq.${encodeURIComponent(slug)}` : `slug=eq.${encodeURIComponent(slug)}`;
  const response = await supabaseRequest(`service_categories?select=id,name,slug&is_active=eq.true&${filter}&limit=1`);
  if (!response) throw new Error('Supabase connection is not configured on the API server.');
  if (!response.ok) throw new Error((await response.text().catch(() => "")) || `Category lookup failed (${response.status}).`);
  const rows = await response.json() as any[];
  if (!rows[0]) throw new Error('Selected marketplace category is invalid or inactive.');
  return rows[0] as { id: string; name: string; slug: string };
}
function validateServiceInput(body: Record<string, any>) {
  const title = String(body.title || "").trim(); const shortDescription = String(body.shortDescription || "").trim(); const coverImage = String(body.coverImage || "").trim(); const category = String(body.category || "").trim(); const categoryId = String(body.categoryId || "").trim(); const locationType = String(body.locationType || "").trim() || "Online / Remote"; const status = body.status === "Draft" || body.status === "Archived" ? body.status : "Published"; const deliverables = Array.isArray(body.deliverables) ? body.deliverables.map((item: unknown) => String(item).trim()).filter(Boolean) : [];
  const durationValue = Number(body.durationValue ?? body.duration); const durationUnit = String(body.durationUnit || "minutes").trim().toLowerCase(); const basePrice = Number(body.basePrice ?? body.basePriceNgn); const baseCurrency = String(body.baseCurrency ?? body.currency ?? "NGN").trim().toUpperCase();
  if (!title) throw new Error("Service title is required."); if (!shortDescription) throw new Error("Description is required."); if (!DURATION_LIMITS[durationUnit]) throw new Error("Duration unit must be minutes, hours, days, weeks, or months."); if (!Number.isInteger(durationValue) || durationValue < 1 || durationValue > DURATION_LIMITS[durationUnit]) throw new Error(`Duration must be between 1 and ${DURATION_LIMITS[durationUnit]} ${durationUnit}.`); if (!basePrice || basePrice <= 0) throw new Error("Service price must be greater than 0."); if (!/^[A-Z]{3}$/.test(baseCurrency)) throw new Error("Currency must be a valid 3-letter ISO currency code.");
  return { title, shortDescription, coverImage, deliverables, duration: durationValue * DURATION_MULTIPLIERS[durationUnit], durationValue, durationUnit, basePrice, baseCurrency, category, categoryId, locationType, status };
}
function legacyNgnValue(basePrice: number, currency: string) { return currency === "NGN" ? basePrice : null; }
async function mapCurrentPiQuote(row: any) { const basePrice = Number(row.base_price ?? row.base_price_ngn); const currency = String(row.base_currency || (row.base_price != null ? row.currency : "NGN") || "NGN").toUpperCase(); const quote = await quoteFiatToPi(basePrice, currency); return { ...row, base_price: basePrice, base_currency: currency, calculated_pi_price: quote.piAmount, current_pi_fiat_rate: quote.piFiatRate, pricing_source: quote.source, pricing_quoted_at: quote.quotedAt }; }
router.get("/pi/services", async (req, res) => { const accessToken = String(req.headers.authorization || "").replace(/^Bearer\s+/i, "").trim(); if (!accessToken) return void res.status(401).json({ error: "Pi access token is required." }); try { const piUser = await verifyPiAccessToken(accessToken); if (!piUser) return void res.status(401).json({ error: "Invalid or expired Pi access token." }); const provider = await getProviderByPiUid(piUser.uid); if (!provider) return void res.status(403).json({ error: "No provider profile is linked to this Pi account." }); const response = await supabaseRequest(`services?select=*,providers(*),service_categories(id,name,slug)&provider_id=eq.${encodeURIComponent(provider.id)}&order=created_at.desc`); if (!response) return void res.status(500).json({ error: "Supabase connection is not configured on the API server." }); if (!response.ok) throw new Error((await response.text().catch(() => "")) || `Failed to load provider services (${response.status}).`); const rows = await response.json() as any[]; const services = await Promise.all(rows.map((row) => mapCurrentPiQuote(row))); return void res.json({ services }); } catch (error: any) { req.log.error({ err: error }, "Provider service list failed"); return void res.status(500).json({ error: error?.message || "Failed to load provider services." }); } });
router.post("/pi/services", async (req, res) => { const accessToken = String(req.headers.authorization || "").replace(/^Bearer\s+/i, "").trim(); if (!accessToken) return void res.status(401).json({ error: "Pi access token is required." }); try { const piUser = await verifyPiAccessToken(accessToken); if (!piUser) return void res.status(401).json({ error: "Invalid or expired Pi access token." }); const provider = await getProviderByPiUid(piUser.uid); if (!provider) return void res.status(403).json({ error: "No provider profile is linked to this Pi account." }); if (provider.status !== "Approved") return void res.status(403).json({ error: "Only approved providers can create services." }); const service = validateServiceInput(req.body || {}); const category = await resolveCategoryId(service.categoryId, service.category); const quote = await quoteFiatToPi(service.basePrice, service.baseCurrency); const response = await supabaseRequest("services", { method: "POST", body: JSON.stringify({ title: service.title, short_description: service.shortDescription, cover_image: service.coverImage, deliverables: service.deliverables, duration: service.duration, duration_value: service.durationValue, duration_unit: service.durationUnit, base_price: service.basePrice, base_currency: service.baseCurrency, base_price_ngn: legacyNgnValue(service.basePrice, service.baseCurrency), calculated_pi_price: quote.piAmount, status: service.status, category: category.slug, category_id: category.id, provider_name: provider.full_name, provider_role: provider.role_title || "Specialist", provider_id: provider.id, location_type: service.locationType, featured: false }) }); if (!response) return void res.status(500).json({ error: "Supabase connection is not configured on the API server." }); if (!response.ok) throw new Error((await response.text().catch(() => "")) || `Service creation failed (${response.status}).`); const rows = await response.json() as any[]; return void res.status(201).json({ service: { ...(rows[0] || {}), category_id: category.id, service_categories: category, calculated_pi_price: quote.piAmount, current_pi_fiat_rate: quote.piFiatRate, pricing_source: quote.source, pricing_quoted_at: quote.quotedAt } }); } catch (error: any) { req.log.error({ err: error }, "Provider service creation failed"); return void res.status(400).json({ error: error?.message || "Failed to create service." }); } });
router.patch("/pi/services/:serviceId", async (req, res) => { const serviceId = req.params.serviceId; const accessToken = String(req.headers.authorization || "").replace(/^Bearer\s+/i, "").trim(); if (!accessToken) return void res.status(401).json({ error: "Pi access token is required." }); if (!/^[0-9a-f-]{36}$/i.test(serviceId)) return void res.status(400).json({ error: "A valid serviceId is required." }); try { const piUser = await verifyPiAccessToken(accessToken); if (!piUser) return void res.status(401).json({ error: "Invalid or expired Pi access token." }); const provider = await getProviderByPiUid(piUser.uid); if (!provider) return void res.status(403).json({ error: "No provider profile is linked to this Pi account." }); if (provider.status !== "Approved") return void res.status(403).json({ error: "Only approved providers can edit services." }); const service = validateServiceInput(req.body || {}); const category = await resolveCategoryId(service.categoryId, service.category); const quote = await quoteFiatToPi(service.basePrice, service.baseCurrency); const response = await supabaseRequest(`services?id=eq.${encodeURIComponent(serviceId)}&provider_id=eq.${encodeURIComponent(provider.id)}`, { method: "PATCH", body: JSON.stringify({ title: service.title, short_description: service.shortDescription, cover_image: service.coverImage, deliverables: service.deliverables, duration: service.duration, duration_value: service.durationValue, duration_unit: service.durationUnit, base_price: service.basePrice, base_currency: service.baseCurrency, base_price_ngn: legacyNgnValue(service.basePrice, service.baseCurrency), calculated_pi_price: quote.piAmount, status: service.status, category: category.slug, category_id: category.id, provider_name: provider.full_name, provider_role: provider.role_title || "Specialist", location_type: service.locationType, updated_at: new Date().toISOString() }) }); if (!response) return void res.status(500).json({ error: "Supabase connection is not configured on the API server." }); if (!response.ok) throw new Error((await response.text().catch(() => "")) || `Service update failed (${response.status}).`); const rows = await response.json() as any[]; if (!rows.length) return void res.status(409).json({ error: "Service was not found or does not belong to this provider." }); return void res.json({ service: { ...rows[0], category_id: category.id, service_categories: category, calculated_pi_price: quote.piAmount, current_pi_fiat_rate: quote.piFiatRate, pricing_source: quote.source, pricing_quoted_at: quote.quotedAt } }); } catch (error: any) { req.log.error({ err: error, serviceId }, "Provider service update failed"); return void res.status(400).json({ error: error?.message || "Failed to update service." }); } });
export default router;
