import React, { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Check, Edit3, Eye, Plus, Save, Upload, X } from 'lucide-react';
import { DurationUnit, Service } from '../../types';
import { providerServiceService, ProviderServiceInput } from '../../services/providerServiceService';
import { providerMediaService } from '../../services/providerMediaService';
import { piAuthService } from '../../services/piAuthService';

interface ProviderServicesViewProps { onBack: () => void; }
type ServiceDraft = ProviderServiceInput;
const DEFAULT_DRAFT: ServiceDraft = { title: '', shortDescription: '', coverImage: '', deliverables: [], duration: 60, durationValue: 60, durationUnit: 'minutes', basePrice: 0, baseCurrency: 'NGN', basePriceNgn: 0, category: 'web_dev', locationType: 'Online / Remote', status: 'Draft' };
const categoryOptions = [['web_dev', 'Web Development'], ['landing_page', 'Landing Pages'], ['ux_design', 'UX / UI Design'], ['pi_sdk', 'Pi SDK'], ['consulting', 'Consulting']];
const currencyOptions = [
  ['NGN', 'Nigerian Naira (NGN)'], ['INR', 'Indian Rupee (INR)'], ['PKR', 'Pakistani Rupee (PKR)'], ['VND', 'Vietnamese Dong (VND)'], ['PHP', 'Philippine Peso (PHP)'],
  ['IDR', 'Indonesian Rupiah (IDR)'], ['KRW', 'South Korean Won (KRW)'], ['BRL', 'Brazilian Real (BRL)'], ['BDT', 'Bangladeshi Taka (BDT)'], ['ETB', 'Ethiopian Birr (ETB)'],
  ['RUB', 'Russian Ruble (RUB)'], ['UAH', 'Ukrainian Hryvnia (UAH)'], ['ZAR', 'South African Rand (ZAR)'], ['THB', 'Thai Baht (THB)'], ['MYR', 'Malaysian Ringgit (MYR)'],
  ['KES', 'Kenyan Shilling (KES)'], ['GHS', 'Ghanaian Cedi (GHS)'], ['TRY', 'Turkish Lira (TRY)'], ['CNY', 'Chinese Yuan (CNY)'], ['JPY', 'Japanese Yen (JPY)'],
  ['USD', 'US Dollar (USD)'], ['EUR', 'Euro (EUR)'], ['GBP', 'British Pound (GBP)'], ['CAD', 'Canadian Dollar (CAD)'], ['AUD', 'Australian Dollar (AUD)'],
  ['CHF', 'Swiss Franc (CHF)'], ['SGD', 'Singapore Dollar (SGD)'], ['HKD', 'Hong Kong Dollar (HKD)'], ['AED', 'UAE Dirham (AED)'], ['SAR', 'Saudi Riyal (SAR)'],
  ['MXN', 'Mexican Peso (MXN)'], ['COP', 'Colombian Peso (COP)'], ['ARS', 'Argentine Peso (ARS)'], ['PLN', 'Polish Złoty (PLN)'], ['CZK', 'Czech Koruna (CZK)'],
  ['SEK', 'Swedish Krona (SEK)'], ['NOK', 'Norwegian Krone (NOK)'], ['DKK', 'Danish Krone (DKK)'], ['NZD', 'New Zealand Dollar (NZD)']
];
const durationLimits: Record<DurationUnit, number> = { minutes: 59, hours: 24, days: 30, weeks: 4, months: 12 };
const durationLabels: Record<DurationUnit, string> = { minutes: 'Minutes', hours: 'Hours', days: 'Days', weeks: 'Weeks', months: 'Months' };
const inputClass = 'w-full px-3.5 py-2.5 rounded-xl border border-zinc-200 bg-white text-sm text-zinc-900 outline-none focus:border-orange-500 focus:ring-2 focus:ring-orange-100 transition';
const labelClass = 'block text-[11px] font-black uppercase tracking-wider text-zinc-500 mb-1.5';

export const ProviderServicesView: React.FC<ProviderServicesViewProps> = ({ onBack }) => {
  const [services, setServices] = useState<Service[]>([]); const [loading, setLoading] = useState(true); const [editingId, setEditingId] = useState<string | null>(null); const [isCreating, setIsCreating] = useState(false); const [draft, setDraft] = useState<ServiceDraft>(DEFAULT_DRAFT); const [deliverablesText, setDeliverablesText] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [saving, setSaving] = useState(false); const [uploadingCover, setUploadingCover] = useState(false); const [preview, setPreview] = useState<Service | null>(null);
  const load = async () => { setLoading(true); setError(''); try { setServices(await providerServiceService.list()); } catch (e: any) { setError(e?.message || 'Unable to load your services.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const editingService = useMemo(() => services.find((service) => service.id === editingId) || null, [services, editingId]);
  const startCreate = () => { setEditingId(null); setDraft(DEFAULT_DRAFT); setDeliverablesText(''); setError(''); setNotice(''); setIsCreating(true); };
  const startEdit = (service: Service) => { const unit = service.durationUnit || 'minutes'; const value = service.durationValue || service.durationMinutes || 60; const currency = String(service.currency || 'NGN').toUpperCase(); setEditingId(service.id); setDraft({ title: service.name, shortDescription: service.description || '', coverImage: service.coverImageUrl || '', deliverables: service.included || [], duration: service.durationMinutes, durationValue: value, durationUnit: unit, basePrice: service.basePrice || service.priceNGN || 0, baseCurrency: currency, basePriceNgn: currency === 'NGN' ? service.basePrice || service.priceNGN || 0 : 0, category: service.category || 'web_dev', locationType: service.locationType || 'Online / Remote', status: service.status || 'Draft' }); setDeliverablesText((service.included || []).join('\n')); setError(''); setNotice(''); setIsCreating(false); };
  const closeEditor = () => { setEditingId(null); setIsCreating(false); setError(''); setNotice(''); };
  const update = <K extends keyof ServiceDraft>(key: K, value: ServiceDraft[K]) => setDraft((current) => ({ ...current, [key]: value }));
  const save = async () => { setSaving(true); setError(''); setNotice(''); const currency = String(draft.baseCurrency || 'NGN').toUpperCase(); const basePrice = Number(draft.basePrice || (currency === 'NGN' ? draft.basePriceNgn : 0)); const payload: ServiceDraft = { ...draft, baseCurrency: currency, basePrice, basePriceNgn: currency === 'NGN' ? basePrice : 0, title: draft.title.trim(), shortDescription: draft.shortDescription.trim(), coverImage: draft.coverImage.trim(), deliverables: deliverablesText.split('\n').map((item) => item.trim()).filter(Boolean), duration: draft.durationValue * ({ minutes: 1, hours: 60, days: 1440, weeks: 10080, months: 43200 } as Record<DurationUnit, number>)[draft.durationUnit] }; try { if (!payload.title || !payload.shortDescription || !payload.basePrice || payload.basePrice <= 0) throw new Error('Title, description and a valid service price are required.'); if (!payload.durationValue || payload.durationValue < 1 || payload.durationValue > durationLimits[payload.durationUnit]) throw new Error(`Duration must be between 1 and ${durationLimits[payload.durationUnit]} ${payload.durationUnit}.`); if (editingService) { const saved = await providerServiceService.update(editingService.id, payload); setServices((current) => current.map((item) => item.id === saved.id ? saved : item)); setNotice('Service updated successfully.'); } else { const saved = await providerServiceService.create(payload); setServices((current) => [saved, ...current]); setNotice('Service created successfully.'); } setEditingId(null); setIsCreating(false); } catch (e: any) { setError(e?.message || 'Unable to save service.'); } finally { setSaving(false); } };
  const uploadCover = async (file: File) => { const user = piAuthService.getStoredUser(); if (!user?.accessToken || !user.uid) { setError('Please sign in with Pi Network first.'); return; } setUploadingCover(true); setError(''); try { const result = await providerMediaService.uploadServiceCover(file, { providerIdentifier: user.uid, piAccessToken: user.accessToken }); update('coverImage', result.publicUrl); setNotice('Cover image uploaded.'); } catch (e: any) { setError(e?.message || 'Cover image upload failed.'); } finally { setUploadingCover(false); } };

  return <div className="space-y-6 pb-12 animate-in fade-in duration-200">
    <div className="flex items-center justify-between gap-3"><button onClick={onBack} className="px-3.5 py-2 rounded-full bg-zinc-100 text-zinc-800 text-xs font-bold hover:bg-zinc-200 transition cursor-pointer"><ArrowLeft className="inline w-4 h-4 mr-1" />Back</button><button onClick={startCreate} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-orange-600 hover:bg-orange-500 text-white text-xs font-black transition cursor-pointer"><Plus className="w-4 h-4" />Create Service</button></div>
    <div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-orange-600">Provider Services</p><h1 className="text-2xl sm:text-3xl font-black tracking-tight text-zinc-950 mt-1">Create and manage your services</h1><p className="text-sm text-zinc-500 mt-2 max-w-2xl">Publish the services you offer on W3C Pi Bookings. Your provider profile is automatically attached to every service.</p></div>
    {error && <div className="px-4 py-3 rounded-xl bg-red-50 border border-red-100 text-xs font-semibold text-red-700">{error}</div>}{notice && <div className="px-4 py-3 rounded-xl bg-green-50 border border-green-100 text-xs font-semibold text-green-700">{notice}</div>}
    {(isCreating || editingId) && <section className="border-y border-zinc-200 py-6 space-y-5"><div className="flex items-center justify-between gap-3"><div><h2 className="text-lg font-black text-zinc-950">{editingService ? 'Edit Service' : 'Create Service'}</h2><p className="text-xs text-zinc-500 mt-1">Set the currency you use to price this service. Pi is calculated from the live fiat rate.</p></div><button onClick={closeEditor} className="p-2 rounded-full text-zinc-500 hover:bg-zinc-100 cursor-pointer" aria-label="Close editor"><X className="w-5 h-5" /></button></div>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
        <div className="lg:col-span-2"><label className={labelClass}>Cover Image</label><div className="flex items-center gap-3"><label className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-orange-50 text-orange-700 text-xs font-black cursor-pointer hover:bg-orange-100"><Upload className="w-4 h-4" />{uploadingCover ? 'Uploading…' : 'Upload Cover Image'}<input type="file" accept="image/png,image/jpeg,image/webp" className="hidden" disabled={uploadingCover} onChange={(e) => { const file = e.target.files?.[0]; if (file) void uploadCover(file); e.currentTarget.value = ''; }} /></label>{draft.coverImage && <img src={draft.coverImage} alt="Cover preview" className="w-20 h-14 rounded-xl object-cover border border-zinc-200" />}</div></div>
        <div><label className={labelClass}>Service Title</label><input className={inputClass} value={draft.title} onChange={(e) => update('title', e.target.value)} placeholder="e.g. Business Website Development" /></div>
        <div><label className={labelClass}>Category</label><select className={inputClass} value={draft.category} onChange={(e) => update('category', e.target.value)}>{categoryOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>
        <div className="lg:col-span-2"><label className={labelClass}>Description</label><textarea className={`${inputClass} min-h-32 resize-y`} value={draft.shortDescription} onChange={(e) => update('shortDescription', e.target.value)} placeholder="Explain clearly what the client receives." /></div>
        <div className="lg:col-span-2"><label className={labelClass}>Deliverables / Inclusions</label><textarea className={`${inputClass} min-h-32 resize-y`} value={deliverablesText} onChange={(e) => setDeliverablesText(e.target.value)} placeholder="One deliverable per line" /></div>
        <div><label className={labelClass}>Service Duration</label><div className="grid grid-cols-[1fr_1.35fr] gap-2"><input type="number" min={1} max={durationLimits[draft.durationUnit]} className={inputClass} value={draft.durationValue} onChange={(e) => update('durationValue', Number(e.target.value))} /><select className={inputClass} value={draft.durationUnit} onChange={(e) => { const unit = e.target.value as DurationUnit; update('durationUnit', unit); if (draft.durationValue > durationLimits[unit]) update('durationValue', durationLimits[unit]); }}>{(Object.keys(durationLabels) as DurationUnit[]).map((unit) => <option key={unit} value={unit}>{durationLabels[unit]} (max {durationLimits[unit]})</option>)}</select></div><p className="text-[10px] text-zinc-400 mt-1">Set how long you expect to take to deliver this service. This starts when you accept a paid booking.</p></div>
        <div><label className={labelClass}>Pricing Currency</label><select className={inputClass} value={draft.baseCurrency || 'NGN'} onChange={(e) => { const currency = e.target.value; update('baseCurrency', currency); if (currency !== 'NGN') update('basePriceNgn', 0); else update('basePriceNgn', Number(draft.basePrice || 0)); }}>{currencyOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><p className="text-[10px] text-zinc-400 mt-1">Choose the fiat currency your service price is denominated in.</p></div>
        <div><label className={labelClass}>Base Price ({String(draft.baseCurrency || 'NGN').toUpperCase()})</label><input type="number" min={0.01} step="0.01" className={inputClass} value={draft.basePrice || ''} onChange={(e) => update('basePrice', Number(e.target.value))} placeholder={draft.baseCurrency === 'NGN' ? '50000' : '100'} /></div>
        <div className="lg:col-span-2 p-4 rounded-2xl bg-orange-50/60 border border-orange-100"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-wider text-orange-700">Pi Price</p><p className="text-xs text-zinc-500 mt-1">Calculated from the live market rate when the service is saved.</p></div><div className="text-xl font-black text-orange-700">{draft.basePrice > 0 ? 'Live rate → Pi quote' : 'Enter a price'}</div></div></div>
        <div><label className={labelClass}>Service Mode</label><select className={inputClass} value={draft.locationType} onChange={(e) => update('locationType', e.target.value)}><option>Online / Remote</option><option>On-site</option><option>Hybrid</option></select></div>
        <div><label className={labelClass}>Status</label><select className={inputClass} value={draft.status} onChange={(e) => update('status', e.target.value as ServiceDraft['status'])}><option value="Draft">Draft</option><option value="Published">Published</option><option value="Archived">Archived</option></select></div>
      </div>
      <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-end gap-2 pt-2 border-t border-zinc-100"><button onClick={closeEditor} className="px-4 py-2.5 rounded-xl text-xs font-bold text-zinc-600 hover:bg-zinc-100 cursor-pointer">Cancel</button><button onClick={save} disabled={saving || uploadingCover} className="inline-flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl bg-orange-600 hover:bg-orange-500 disabled:opacity-50 text-white text-xs font-black cursor-pointer"><Save className="w-4 h-4" />{saving ? 'Saving…' : editingService ? 'Save Changes' : 'Create Service'}</button></div>
    </section>}
    <section><div className="flex items-center justify-between mb-3"><h2 className="text-sm font-black text-zinc-900">Your Services</h2><span className="text-[11px] font-bold text-zinc-400">{services.length} {services.length === 1 ? 'service' : 'services'}</span></div>{loading ? <div className="py-12 text-center text-xs font-semibold text-zinc-400">Loading your services…</div> : services.length === 0 ? <div className="py-12 border-y border-zinc-200 text-center"><p className="text-sm font-bold text-zinc-700">No services yet.</p><p className="text-xs text-zinc-400 mt-1">Create your first service to start offering it to clients.</p></div> : <div className="divide-y divide-zinc-200 border-y border-zinc-200">{services.map((service) => <div key={service.id} className="py-5 flex flex-col sm:flex-row gap-4 sm:items-center"><div className="w-16 h-16 rounded-xl overflow-hidden bg-zinc-100 shrink-0">{service.coverImageUrl ? <img src={service.coverImageUrl} alt="" className="w-full h-full object-cover" /> : <div className="w-full h-full flex items-center justify-center text-[10px] font-bold text-zinc-400">No image</div>}</div><div className="flex-1 min-w-0"><div className="flex items-center gap-2 flex-wrap"><h3 className="font-black text-sm text-zinc-900 truncate">{service.name}</h3><span className={`px-2 py-0.5 rounded-full text-[9px] font-black ${service.status === 'Published' ? 'bg-green-50 text-green-700' : service.status === 'Archived' ? 'bg-zinc-100 text-zinc-500' : 'bg-amber-50 text-amber-700'}`}>{service.status}</span></div><p className="text-xs text-zinc-500 mt-1 line-clamp-2">{service.description}</p><div className="text-[11px] text-zinc-400 font-semibold mt-1">{service.currency || 'NGN'} {service.basePrice?.toLocaleString(undefined, { maximumFractionDigits: 2 }) || service.priceNGN.toLocaleString()} · {service.durationValue || service.durationMinutes} {durationLabels[service.durationUnit || 'minutes'].toLowerCase()} · {service.pricePi || 0} π</div></div><div className="flex items-center gap-2 shrink-0"><button onClick={() => setPreview(service)} className="inline-flex items-center gap-1.5 px-3 py-2 rounded-xl bg-zinc-100 text-zinc-700 text-[11px] font-bold hover:bg-zinc-200 cursor-pointer"><Eye className="w-3.5 h-3.5" />Preview</button><button onClick={() => startEdit(service)} className="inline-flex items-center gap-1.5 px-3 py-2 rounded-xl bg-orange-50 text-orange-700 text-[11px] font-bold hover:bg-orange-100 cursor-pointer"><Edit3 className="w-3.5 h-3.5" />Edit</button></div></div>)}</div>}</section>
    {preview && <div className="fixed inset-0 z-50 bg-zinc-950/50 backdrop-blur-sm flex items-end sm:items-center justify-center p-0 sm:p-5" onClick={() => setPreview(null)}><div className="bg-white w-full sm:max-w-2xl max-h-[92vh] overflow-y-auto rounded-t-3xl sm:rounded-3xl" onClick={(e) => e.stopPropagation()}><div className="flex items-center justify-between p-4 border-b border-zinc-100"><div><p className="text-[10px] font-black uppercase tracking-wider text-orange-600">Client Preview</p><h2 className="font-black text-zinc-950">{preview.name}</h2></div><button onClick={() => setPreview(null)} className="p-2 rounded-full hover:bg-zinc-100 cursor-pointer"><X className="w-5 h-5" /></button></div>{preview.coverImageUrl && <img src={preview.coverImageUrl} alt={preview.name} className="w-full h-52 object-cover" />}<div className="p-5 space-y-5"><div><span className="text-[10px] font-black uppercase tracking-wider text-orange-600">{preview.category.replace('_', ' ')}</span><h3 className="text-xl font-black mt-1">{preview.name}</h3><p className="text-sm text-zinc-600 mt-2 whitespace-pre-line">{preview.description}</p></div><div className="grid grid-cols-2 gap-3 text-xs"><div className="p-3 bg-zinc-50 rounded-xl"><span className="block text-zinc-400 font-bold">Price</span><span className="font-black">{preview.basePrice || preview.priceNGN} {preview.currency || 'NGN'} → {preview.pricePi} π</span></div><div className="p-3 bg-zinc-50 rounded-xl"><span className="block text-zinc-400 font-bold">Duration</span><span className="font-black">{preview.durationValue || preview.durationMinutes} {durationLabels[preview.durationUnit || 'minutes'].toLowerCase()}</span></div></div><div><h4 className="text-xs font-black uppercase tracking-wider text-zinc-500 mb-2">Deliverables</h4><ul className="space-y-2">{preview.included.map((item, index) => <li key={index} className="flex gap-2 text-xs text-zinc-700"><Check className="w-3.5 h-3.5 text-orange-600 shrink-0" />{item}</li>)}</ul></div></div></div></div>}
  </div>;
};