import React, { useEffect, useState } from 'react';
import { Booking, DeliveryAttachment } from '../../types';
import { Clock, Copy, FileText, Hash, Paperclip, X, Upload, CheckCircle2 } from 'lucide-react';
import { toast } from '../../hooks/use-toast';
import { formatBookingCreated } from '../../lib/utils';
import { formatDuration } from '../../lib/formatDuration';
import { isPendingAcceptance, getRemainingMs, formatCountdown, isAcceptanceExpired } from '../../lib/acceptanceCountdown';
import { getProjectRemainingMs, formatProjectCountdown } from '../../lib/projectTimer';
import { bookingService } from '../../services/bookingService';
import { clientStatusBadge } from '../../components/ClientAcceptanceBanner';

interface ProviderBookingDetailsProps { booking: Booking; onClose: () => void; onOpenChat?: (bookingId: string) => void; onBookingUpdated?: (bookings: Booking[]) => void; }
const compactValue = (value: string, start = 10, end = 8) => value.length > start + end + 3 ? `${value.slice(0, start)}...${value.slice(-end)}` : value;
export const ProviderBookingDetails: React.FC<ProviderBookingDetailsProps> = ({ booking, onClose, onBookingUpdated }) => {
  const [tick, setTick] = useState(0); const [showDeliveryModal, setShowDeliveryModal] = useState(false); const [deliveryNotes, setDeliveryNotes] = useState(booking.delivery_notes || ''); const [deliveryFiles, setDeliveryFiles] = useState<DeliveryAttachment[]>(booking.delivery_attachments || []); const [submittingDelivery, setSubmittingDelivery] = useState(false); const transactionHash = booking.piTxHash || '';
  useEffect(() => { const id = setInterval(() => setTick((t) => t + 1), 1000); return () => clearInterval(id); }, []); void tick;
  const pendingAccept = isPendingAcceptance(booking); const expired = isAcceptanceExpired(booking.acceptance_deadline); const remainLabel = formatCountdown(getRemainingMs(booking.acceptance_deadline)); const projectRemaining = getProjectRemainingMs(booking.project_deadline); const projectExpired = booking.status === 'In Progress' && Boolean(booking.project_deadline) && projectRemaining <= 0; const projectTimerLabel = formatProjectCountdown(projectRemaining); const canDeliver = booking.status === 'In Progress' && booking.escrow_status === 'paid_escrowed';
  const statusBadge = clientStatusBadge(booking);
  const submitDelivery = async () => { if (!deliveryNotes.trim() && deliveryFiles.length === 0) { toast({ title: 'Delivery details required', description: 'Add delivery notes or a deliverable before submitting.', variant: 'destructive' }); return; } setSubmittingDelivery(true); try { const updated = await bookingService.submitDeliveryAsync(booking.id, deliveryNotes, deliveryFiles); onBookingUpdated?.(updated); setShowDeliveryModal(false); toast({ title: 'Service marked as delivered', description: 'The client has been notified in the booking chat.' }); } catch (error: any) { toast({ title: 'Delivery failed', description: error?.message || 'Could not submit delivery.', variant: 'destructive' }); } finally { setSubmittingDelivery(false); } };
  const handleFiles = (files: FileList | null) => { if (!files) return; const additions: DeliveryAttachment[] = Array.from(files).slice(0, 10).map((file) => ({ id: `${Date.now()}-${file.name}-${Math.random().toString(36).slice(2, 7)}`, name: file.name, type: file.type, size: file.size })); setDeliveryFiles((items) => [...items, ...additions].slice(0, 20)); };
  const copy = async (value: string, label: string) => { try { await navigator.clipboard.writeText(value); toast({ title: `${label} copied`, description: 'The value is ready to paste.' }); } catch { toast({ title: 'Copy failed', description: `Could not copy the ${label.toLowerCase()}.`, variant: 'destructive' }); } };
  return (<div className="fixed inset-0 z-50 bg-zinc-100 overflow-y-auto animate-in fade-in duration-150"><div className="min-h-full w-full pb-28"><header className="sticky top-0 z-20 bg-white/95 backdrop-blur border-b border-zinc-200"><div className="max-w-3xl mx-auto px-4 sm:px-6 py-3 flex items-center justify-between gap-3"><button type="button" onClick={onClose} className="inline-flex items-center gap-2 text-xs font-black text-zinc-700 hover:text-zinc-950 transition" aria-label="Close booking details"><X className="w-4 h-4" /> Close</button><span className="text-[10px] font-black uppercase tracking-[0.16em] text-zinc-400">Booking receipt</span><span className="w-12" /></div></header>
    <main className="max-w-3xl mx-auto px-3 sm:px-6 py-3 sm:py-5"><article className="bg-white shadow-sm border border-zinc-200 rounded-sm overflow-hidden"><div className="px-4 sm:px-6 pt-4 pb-3 text-center border-b border-dashed border-zinc-300"><div className="w-8 h-8 mx-auto rounded-full bg-zinc-950 text-white flex items-center justify-center mb-1.5"><FileText className="w-4 h-4" /></div><p className="text-[8px] font-black uppercase tracking-[0.2em] text-zinc-400">W3C Pi Bookings</p><h1 className="text-lg sm:text-xl font-black tracking-tight text-zinc-950 mt-0.5">Booking Details</h1><p className="text-[10px] text-zinc-500 mt-0.5 truncate">{booking.serviceName}</p></div>
      <div className="px-4 sm:px-6 py-3 border-b border-zinc-200"><div className="grid grid-cols-2 gap-x-4 gap-y-2.5"><div className="min-w-0"><p className="text-[8px] font-black uppercase tracking-wider text-zinc-400">Client</p><p className="text-sm font-black text-zinc-950 truncate mt-0.5">{booking.clientName || 'Client'}</p>{booking.clientPiUsername && <p className="text-[9px] text-zinc-500 truncate">@{booking.clientPiUsername.replace(/^@+/, '')}</p>}</div><div className="text-right min-w-0"><p className="text-[8px] font-black uppercase tracking-wider text-zinc-400">Status</p><span className={`inline-flex items-center gap-1 mt-0.5 text-[9px] font-extrabold ${statusBadge.classes}`}>{statusBadge.dot && <span className={`w-1.5 h-1.5 rounded-full ${statusBadge.dot}`} />}{statusBadge.label}</span></div><div><p className="text-[8px] font-black uppercase tracking-wider text-zinc-400">Service Value</p><p className="text-sm font-black text-zinc-950 mt-0.5">{Number(booking.pricePi || 0).toFixed(2)} π</p></div><div className="text-right"><p className="text-[8px] font-black uppercase tracking-wider text-zinc-400">Duration</p><p className="text-xs font-bold text-zinc-900 mt-0.5">{booking.durationMinutes ? formatDuration(booking.durationMinutes) : '—'}</p></div><div><p className="text-[8px] font-black uppercase tracking-wider text-zinc-400">Booked On</p><p className="text-[10px] font-bold text-zinc-900 mt-0.5">{formatBookingCreated(booking.createdAt)}</p></div><div className="text-right"><p className="text-[8px] font-black uppercase tracking-wider text-zinc-400">Booking ID</p><button type="button" onClick={() => copy(booking.id, 'Booking ID')} className="inline-flex items-center gap-1 text-[10px] font-mono text-zinc-700 mt-0.5 hover:text-amber-700">{compactValue(booking.id)}<Copy className="w-3 h-3 text-zinc-400" /></button></div></div></div>
      <section className="px-4 sm:px-6 py-3 border-b border-zinc-200"><div className="flex items-center justify-between gap-3 mb-1.5"><h2 className="text-[9px] font-black uppercase tracking-[0.16em] text-zinc-500">Client's Brief</h2></div>{booking.notes ? <p className="text-[11px] leading-4 text-zinc-800 whitespace-pre-wrap line-clamp-3">{booking.notes}</p> : <p className="text-[11px] text-zinc-400">No project brief provided.</p>}</section>
      {booking.attachments && booking.attachments.length > 0 && <section className="px-4 sm:px-6 py-3 border-b border-zinc-200"><div className="flex items-center justify-between gap-3 mb-1.5"><h2 className="text-[9px] font-black uppercase tracking-[0.16em] text-zinc-500">Attachments</h2><span className="text-[8px] text-zinc-400">{booking.attachments.length}</span></div><div className="space-y-1">{booking.attachments.slice(0, 3).map((attachment) => <div key={attachment.id} className="flex items-center gap-2 text-[10px]"><Paperclip className="w-3 h-3 text-zinc-400 shrink-0" /><span className="truncate text-zinc-800">{attachment.name}</span></div>)}{booking.attachments.length > 3 && <p className="text-[9px] text-zinc-400">+{booking.attachments.length - 3} more attachment(s)</p>}</div></section>}
      {pendingAccept && <section className="px-4 sm:px-6 py-3 border-b border-zinc-200"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-1.5"><Clock className="w-3.5 h-3.5 text-zinc-500" /><h2 className="text-[9px] font-black uppercase tracking-[0.16em] text-zinc-500">Acceptance Window</h2></div><span className={`text-base font-black tabular-nums ${expired ? 'text-rose-700' : 'text-zinc-950'}`}>{expired ? 'Expired' : remainLabel}</span></div>{booking.acceptance_deadline && <p className="text-[9px] text-zinc-500 mt-0.5">Deadline: {new Date(booking.acceptance_deadline).toLocaleString()}</p>}</section>}
      {booking.status === 'In Progress' && booking.project_deadline && <section className="px-4 sm:px-6 py-3 border-b border-zinc-200"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-1.5"><Clock className="w-3.5 h-3.5 text-zinc-500" /><h2 className="text-[9px] font-black uppercase tracking-[0.16em] text-zinc-500">Project Timeline</h2></div><span className={`text-xl font-black tabular-nums ${projectExpired ? 'text-rose-700' : 'text-zinc-950'}`}>{projectExpired ? '00:00' : projectTimerLabel}</span></div><p className="text-[9px] text-zinc-500 mt-0.5">Deadline: {new Date(booking.project_deadline).toLocaleString()}</p></section>}
      {booking.status === 'Delivered' && <section className="px-4 sm:px-6 py-3 border-b border-zinc-200"><div className="flex items-center gap-1.5 mb-1"><CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" /><h2 className="text-[9px] font-black uppercase tracking-[0.16em] text-zinc-500">Latest Delivery</h2></div><p className="text-[10px] leading-4 text-zinc-600">Delivered {booking.delivered_at ? new Date(booking.delivered_at).toLocaleString() : ''}. Escrow remains held pending client review.</p>{booking.delivery_notes && <p className="text-[10px] leading-4 text-zinc-800 mt-1.5 pt-1.5 border-t border-dashed border-zinc-200 line-clamp-2">{booking.delivery_notes}</p>}</section>}
      {transactionHash && <section className="px-4 sm:px-6 py-3 border-b border-zinc-200"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-1.5"><Hash className="w-3.5 h-3.5 text-zinc-500" /><h2 className="text-[9px] font-black uppercase tracking-[0.16em] text-zinc-500">Pi Transaction</h2></div><button type="button" onClick={() => copy(transactionHash, 'Transaction hash')} className="shrink-0 p-1 rounded-md bg-zinc-50 border border-zinc-200"><Copy className="w-3 h-3" /></button></div><p className="mt-1 font-mono text-[9px] text-zinc-700 truncate">{compactValue(transactionHash, 12, 10)}</p></section>}
      {booking.rejection_reason && <section className="px-4 sm:px-6 py-3 border-b border-zinc-200"><h2 className="text-[9px] font-black uppercase tracking-[0.16em] text-rose-700">Cancellation Reason</h2><p className="text-[10px] leading-4 text-rose-900 mt-1 line-clamp-2">{booking.rejection_reason}</p></section>}
      <footer className="px-4 sm:px-6 py-2.5 text-center"><p className="text-[8px] text-zinc-400">Keep this record for your booking history and dispute or appeal reference.</p></footer></article></main>
    <div className="fixed bottom-0 inset-x-0 z-30 bg-white/97 backdrop-blur border-t border-zinc-200 safe-area-pb"><div className="max-w-3xl mx-auto px-4 sm:px-6 py-3 flex items-center justify-center">{canDeliver ? <button type="button" onClick={() => { setDeliveryNotes(''); setDeliveryFiles([]); setShowDeliveryModal(true); }} className="w-full sm:w-auto min-w-64 py-3 px-8 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-black flex items-center justify-center gap-2 transition shadow-sm"><Upload className="w-4 h-4" />Mark as Delivered</button> : <div className="text-center"><p className="text-[9px] font-extrabold uppercase tracking-wider text-zinc-400">Booking action</p><p className="text-xs font-bold text-zinc-700 mt-0.5">{booking.status === 'Delivered' ? 'Waiting for client review' : booking.status === 'Completed' ? 'Booking completed' : 'No action required'}</p></div>}</div></div>
  </div>{showDeliveryModal && <div className="fixed inset-0 z-[70] bg-black/50 backdrop-blur-sm flex items-end sm:items-center justify-center p-0 sm:p-4" role="dialog" aria-modal="true" aria-labelledby="submit-delivery-title"><div className="w-full sm:max-w-lg bg-white rounded-t-3xl sm:rounded-3xl shadow-2xl overflow-hidden max-h-[90vh] flex flex-col"><div className="px-5 py-4 border-b border-zinc-200 flex items-center justify-between gap-3"><div><h2 id="submit-delivery-title" className="text-base font-black text-zinc-950">Submit Delivery</h2><p className="text-[11px] text-zinc-500 mt-0.5">Tell the client what you delivered and attach proof.</p></div><button type="button" onClick={() => setShowDeliveryModal(false)} className="p-2 rounded-xl bg-zinc-100 hover:bg-zinc-200 text-zinc-700"><X className="w-4 h-4" /></button></div><div className="p-5 space-y-4 overflow-y-auto"><div><label className="text-[10px] font-black uppercase tracking-wider text-zinc-500">Delivery notes</label><textarea autoFocus value={deliveryNotes} onChange={(e) => setDeliveryNotes(e.target.value)} rows={5} placeholder="Describe what you delivered to the client…" className="mt-2 w-full p-3 rounded-xl bg-zinc-50 border border-zinc-200 text-sm text-zinc-900 focus:outline-none focus:border-emerald-500 resize-none" /></div><div><label className="text-[10px] font-black uppercase tracking-wider text-zinc-500">Delivery proof</label><label className="mt-2 flex items-center justify-center gap-2 py-4 rounded-xl bg-zinc-50 border border-dashed border-zinc-300 text-zinc-700 text-xs font-black cursor-pointer hover:bg-zinc-100"><Paperclip className="w-4 h-4" /><span>Add deliverable / proof</span><input type="file" multiple className="hidden" onChange={(e) => handleFiles(e.target.files)} /></label>{deliveryFiles.length > 0 && <div className="mt-2 space-y-1">{deliveryFiles.map((file) => <div key={file.id} className="flex items-center justify-between gap-2 text-xs bg-zinc-50 rounded-lg px-3 py-2"><span className="truncate font-medium text-zinc-800">{file.name}</span><button type="button" onClick={() => setDeliveryFiles((items) => items.filter((item) => item.id !== file.id))} className="text-zinc-400 hover:text-rose-600"><X className="w-3.5 h-3.5" /></button></div>)}</div>}</div></div><div className="p-4 border-t border-zinc-200 flex gap-2"><button type="button" onClick={() => setShowDeliveryModal(false)} className="flex-1 py-3 rounded-xl bg-zinc-100 hover:bg-zinc-200 text-zinc-800 text-xs font-black">Cancel</button><button type="button" disabled={submittingDelivery} onClick={submitDelivery} className="flex-[2] py-3 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-black flex items-center justify-center gap-2 disabled:opacity-50">{submittingDelivery ? 'Submitting…' : <><CheckCircle2 className="w-4 h-4" />Mark as Delivered</>}</button></div></div></div>}</div>);
};