import React, { useState } from 'react';
import { PiUser, PortfolioItem } from '../types';
import { ArrowLeft, User, Briefcase, FileText, ArrowRight, ShieldCheck, Wallet, MapPin, Tag, Globe, Clock, Award, Camera, ImageIcon, Plus, Trash2 } from 'lucide-react';
import { ProfilePhotoUploader } from './media/ProfilePhotoUploader';
import { PortfolioUploader } from './media/PortfolioUploader';

export interface SocialLink { platform: string; url: string; }

export interface BecomeProviderDetails {
  fullName: string; piUsername: string; roleTitle: string; headline?: string; bio: string; photoUrl: string; piWalletAddress: string;
  location?: string; specialties?: string[]; skills?: string[]; experienceLevel?: string; yearsExperience?: number;
  availabilityStatus?: string; responseTime?: string; languages?: string[]; serviceMode?: string; website?: string;
  socialLinks?: SocialLink[]; portfolioImages?: string[]; portfolioItems?: PortfolioItem[];
}

interface BecomeProviderStepProps { piUser: PiUser | null; onBack: () => void; onSubmit: (details: BecomeProviderDetails) => void; submitting?: boolean; }

export const BecomeProviderStep: React.FC<BecomeProviderStepProps> = ({ piUser, onBack, onSubmit, submitting = false }) => {
  const [fullName, setFullName] = useState(piUser?.username || ''); const [piUsername, setPiUsername] = useState(piUser?.username ? `@${piUser.username}` : '');
  const [roleTitle, setRoleTitle] = useState(''); const [headline, setHeadline] = useState(''); const [bio, setBio] = useState(''); const [photoUrl, setPhotoUrl] = useState('');
  const [piWalletAddress, setPiWalletAddress] = useState(''); const [location, setLocation] = useState(''); const [experienceLevel, setExperienceLevel] = useState('Intermediate');
  const [yearsExperience, setYearsExperience] = useState('3'); const [serviceMode, setServiceMode] = useState('Remote'); const [specialtiesInput, setSpecialtiesInput] = useState('');
  const [skillsInput, setSkillsInput] = useState(''); const [languagesInput, setLanguagesInput] = useState('English'); const [availabilityStatus, setAvailabilityStatus] = useState('available');
  const [responseTime, setResponseTime] = useState('Within 1 hour'); const [website, setWebsite] = useState(''); const [socialLinks, setSocialLinks] = useState<SocialLink[]>([]);
  const [portfolioItems, setPortfolioItems] = useState<PortfolioItem[]>([]);
  const inputClass = 'w-full px-4 py-2.5 rounded-xl bg-zinc-50 border border-zinc-200 text-xs text-zinc-900 placeholder-zinc-400 focus:outline-none focus:border-amber-500 focus:bg-white transition';
  const split = (value: string) => value.split(',').map(s => s.trim()).filter(Boolean);
  const addSocialLink = () => setSocialLinks(links => [...links, { platform: '', url: '' }]);
  const updateSocialLink = (index: number, field: keyof SocialLink, value: string) => setSocialLinks(links => links.map((link, i) => i === index ? { ...link, [field]: value } : link));
  const removeSocialLink = (index: number) => setSocialLinks(links => links.filter((_, i) => i !== index));
  const handleSubmit = (e: React.FormEvent) => { e.preventDefault(); const portfolioImages = portfolioItems.map(item => item.imageUrl || item.path || '').filter(Boolean); onSubmit({
    fullName, piUsername, roleTitle, headline: headline || undefined, bio, photoUrl, piWalletAddress, location: location || undefined,
    specialties: split(specialtiesInput), skills: split(skillsInput), experienceLevel, yearsExperience: yearsExperience ? Number(yearsExperience) : undefined,
    availabilityStatus, responseTime, languages: split(languagesInput), serviceMode, website: website || undefined,
    socialLinks: socialLinks.filter(link => link.platform.trim() && link.url.trim()), portfolioImages, portfolioItems,
  }); };
  const providerIdentifier = piUser?.uid || piUsername || 'provider'; const piAccessToken = piUser?.accessToken;
  return <div className="space-y-4 pb-28 animate-in fade-in slide-in-from-right-4 duration-200">
    <div className="flex items-center justify-between"><button type="button" onClick={onBack} className="flex items-center gap-1.5 px-3.5 py-1.5 rounded-full bg-zinc-100 text-zinc-800 text-xs font-semibold hover:bg-zinc-200 transition"><ArrowLeft className="w-4 h-4" /><span>Back</span></button></div>
    <div className="p-5 rounded-2xl bg-white space-y-1 shadow-md"><h2 className="text-xl font-black text-zinc-900 tracking-tight">Become a Service Provider</h2><p className="text-xs text-zinc-600 leading-relaxed">Create your professional provider profile, showcase your portfolio works, and offer services across the Pi Network ecosystem.</p></div>
    <form onSubmit={handleSubmit} className="space-y-4">
      <section className="p-5 rounded-2xl bg-white space-y-4 shadow-md"><h3 className="text-xs font-black text-zinc-900 uppercase tracking-wider flex items-center gap-2"><User className="w-4 h-4 text-amber-600" />1. Identity & Contact Information</h3>
        <div className="p-4 rounded-xl bg-zinc-50 border border-zinc-200/80 space-y-2"><label className="block text-[11px] font-extrabold text-zinc-700 uppercase tracking-wider flex items-center gap-1.5"><Camera className="w-3.5 h-3.5 text-amber-600" />Profile Photo</label><ProfilePhotoUploader value={photoUrl} onChange={setPhotoUrl} providerIdentifier={providerIdentifier} piAccessToken={piAccessToken} /></div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><div><label className="block text-[11px] font-bold text-zinc-700 mb-1">Full Name / Display Name <span className="text-amber-600">*</span></label><div className="relative"><User className="w-4 h-4 text-zinc-400 absolute left-3.5 top-3" /><input required value={fullName} onChange={e => setFullName(e.target.value)} placeholder="e.g. Alex Johnson" className={`${inputClass} pl-10`} /></div></div><div><label className="block text-[11px] font-bold text-zinc-700 mb-1">Pi Username</label><input value={piUsername} onChange={e => setPiUsername(e.target.value)} placeholder="@username" className={`${inputClass} font-mono`} /></div></div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><div><label className="block text-[11px] font-bold text-zinc-700 mb-1">Professional Role / Title <span className="text-amber-600">*</span></label><div className="relative"><Briefcase className="w-4 h-4 text-zinc-400 absolute left-3.5 top-3" /><input required value={roleTitle} onChange={e => setRoleTitle(e.target.value)} placeholder="e.g. Fullstack Web Developer" className={`${inputClass} pl-10`} /></div></div><div><label className="block text-[11px] font-bold text-zinc-700 mb-1">Professional Headline</label><input value={headline} onChange={e => setHeadline(e.target.value)} placeholder="e.g. Senior Fullstack Engineer & Designer" className={inputClass} /></div></div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><div><label className="block text-[11px] font-bold text-zinc-700 mb-1">Location / Base City</label><div className="relative"><MapPin className="w-4 h-4 text-zinc-400 absolute left-3.5 top-3" /><input value={location} onChange={e => setLocation(e.target.value)} placeholder="e.g. Lagos, Nigeria or Remote" className={`${inputClass} pl-10`} /></div></div><div><label className="block text-[11px] font-bold text-zinc-700 mb-1">Pi Wallet Address (for Escrow Payouts)</label><div className="relative"><Wallet className="w-4 h-4 text-zinc-400 absolute left-3.5 top-3" /><input value={piWalletAddress} onChange={e => setPiWalletAddress(e.target.value)} placeholder="Enter your Pi wallet public key" className={`${inputClass} pl-10 font-mono`} /></div></div></div>
      </section>
      <section className="p-5 rounded-2xl bg-white space-y-3.5 shadow-md"><h3 className="text-xs font-black text-zinc-900 uppercase tracking-wider flex items-center gap-2"><Award className="w-4 h-4 text-amber-600" />2. Skills & Experience</h3><div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><div><label className="block text-[11px] font-bold text-zinc-700 mb-1">Experience Level</label><select value={experienceLevel} onChange={e => setExperienceLevel(e.target.value)} className={inputClass}><option>Entry Level</option><option>Intermediate</option><option>Senior / Expert</option></select></div><div><label className="block text-[11px] font-bold text-zinc-700 mb-1">Years of Experience</label><input type="number" min="0" max="50" value={yearsExperience} onChange={e => setYearsExperience(e.target.value)} className={inputClass} /></div><div><label className="block text-[11px] font-bold text-zinc-700 mb-1">Service Delivery Mode</label><select value={serviceMode} onChange={e => setServiceMode(e.target.value)} className={inputClass}><option>Remote</option><option>Onsite</option><option>Hybrid</option></select></div></div><div><label className="block text-[11px] font-bold text-zinc-700 mb-1">Specialties (comma-separated)</label><div className="relative"><Tag className="w-4 h-4 text-zinc-400 absolute left-3.5 top-3" /><input value={specialtiesInput} onChange={e => setSpecialtiesInput(e.target.value)} placeholder="e.g. UI/UX Design, Brand Identity, Mobile Apps" className={`${inputClass} pl-10`} /></div></div><div><label className="block text-[11px] font-bold text-zinc-700 mb-1">Skills & Technologies (comma-separated)</label><div className="relative"><Tag className="w-4 h-4 text-zinc-400 absolute left-3.5 top-3" /><input value={skillsInput} onChange={e => setSkillsInput(e.target.value)} placeholder="e.g. Figma, React, Tailwind, Photoshop, Node.js" className={`${inputClass} pl-10`} /></div></div><div><label className="block text-[11px] font-bold text-zinc-700 mb-1">Languages Spoken (comma-separated)</label><input value={languagesInput} onChange={e => setLanguagesInput(e.target.value)} placeholder="e.g. English, French, Spanish" className={inputClass} /></div></section>
      <section className="p-5 rounded-2xl bg-white space-y-3.5 shadow-md"><h3 className="text-xs font-black text-zinc-900 uppercase tracking-wider flex items-center gap-2"><FileText className="w-4 h-4 text-amber-600" />3. Bio & Availability</h3><div><label className="block text-[11px] font-bold text-zinc-700 mb-1">Bio / Profile Introduction <span className="text-amber-600">*</span></label><textarea rows={4} required value={bio} onChange={e => setBio(e.target.value)} placeholder="Describe your background, expertise, service approach, and what clients can expect..." className={`${inputClass} leading-relaxed`} /></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><div><label className="block text-[11px] font-bold text-zinc-700 mb-1">Availability Status</label><select value={availabilityStatus} onChange={e => setAvailabilityStatus(e.target.value)} className={inputClass}><option value="available">🟢 Available Now</option><option value="busy">🟡 Busy / Limited Slots</option><option value="away">🔴 Away / Not Accepting Orders</option></select></div><div><label className="block text-[11px] font-bold text-zinc-700 mb-1">Typical Response Time</label><div className="relative"><Clock className="w-4 h-4 text-zinc-400 absolute left-3.5 top-3" /><input value={responseTime} onChange={e => setResponseTime(e.target.value)} placeholder="e.g. Within 1 hour" className={`${inputClass} pl-10`} /></div></div></div></section>
      <section className="p-5 rounded-2xl bg-white space-y-4 shadow-md"><h3 className="text-xs font-black text-zinc-900 uppercase tracking-wider flex items-center gap-2"><Globe className="w-4 h-4 text-amber-600" />4. Portfolio & External Links</h3><div><label className="block text-[11px] font-bold text-zinc-700 mb-1">Website / Portfolio Link</label><div className="relative"><Globe className="w-4 h-4 text-zinc-400 absolute left-3.5 top-3" /><input type="url" value={website} onChange={e => setWebsite(e.target.value)} placeholder="https://yourportfolio.com" className={`${inputClass} pl-10`} /></div></div><div className="space-y-3"><div className="flex items-center justify-between"><label className="block text-[11px] font-extrabold text-zinc-700 uppercase tracking-wider">Social Links</label><button type="button" onClick={addSocialLink} className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-amber-50 text-amber-700 text-[11px] font-bold hover:bg-amber-100 transition"><Plus className="w-3.5 h-3.5" />Add Link</button></div><p className="text-[11px] text-zinc-500">Add professional or community links such as X, Telegram, WhatsApp, LinkedIn, GitHub, or other profiles.</p>{socialLinks.length === 0 ? <div className="rounded-xl border border-dashed border-zinc-200 bg-zinc-50 p-4 text-center text-[11px] text-zinc-400">No social links added yet.</div> : socialLinks.map((link, index) => <div key={index} className="grid grid-cols-[minmax(0,0.35fr)_minmax(0,1fr)_auto] gap-2 items-center"><input value={link.platform} onChange={e => updateSocialLink(index, 'platform', e.target.value)} placeholder="Platform" className={inputClass} /><input type="url" value={link.url} onChange={e => updateSocialLink(index, 'url', e.target.value)} placeholder="https://..." className={inputClass} /><button type="button" onClick={() => removeSocialLink(index)} aria-label="Remove social link" className="p-2 rounded-lg text-zinc-400 hover:text-red-600 hover:bg-red-50 transition"><Trash2 className="w-4 h-4" /></button></div>)}</div><div className="space-y-2"><label className="block text-[11px] font-extrabold text-zinc-700 uppercase tracking-wider flex items-center gap-1.5"><ImageIcon className="w-3.5 h-3.5 text-amber-600" />Portfolio Showcase Images</label><PortfolioUploader items={portfolioItems} onChange={setPortfolioItems} providerIdentifier={providerIdentifier} piAccessToken={piAccessToken} /></div></section>
      <div className="p-4 rounded-2xl bg-emerald-50 shadow-xs flex items-center gap-2.5 text-xs text-emerald-900 font-medium"><ShieldCheck className="w-5 h-5 text-emerald-600 shrink-0" /><span>Client payments are held securely in Pi Smart Escrow and automatically released to your wallet upon confirmed completion.</span></div><div className="fixed bottom-0 left-0 right-0 p-4 bg-white/95 backdrop-blur-md border-t border-zinc-200 z-50"><div className="max-w-md mx-auto flex items-center justify-between gap-3"><div className="text-xs"><span className="block text-zinc-500 font-medium">W3C Pi Network</span><span className="font-bold text-zinc-900">Verified Provider</span></div><button type="submit" disabled={submitting} className="flex-1 py-3.5 px-5 rounded-xl bg-amber-500 hover:bg-amber-400 disabled:opacity-50 disabled:cursor-not-allowed text-white font-black text-sm active:scale-[0.98] transition flex items-center justify-center gap-2 min-h-[48px] shadow-md shadow-amber-500/20"><span>{submitting ? 'Saving Profile...' : 'Complete & Save Profile'}</span>{!submitting && <ArrowRight className="w-4 h-4" />}</button></div></div>
    </form>
  </div>;
};
