import React from 'react';
import { Booking } from '../types';
import { ArrowLeft, Copy, FileText, Hash, MessageSquare, Paperclip } from 'lucide-react';
import { formatBookingCreated } from '../lib/utils';
import { formatDuration } from '../lib/formatDuration';
import { ClientAcceptanceBanner, clientStatusBadge } from './ClientAcceptanceBanner';

interface ClientBookingReceiptProps { booking: Booking; onBack: () => void; onOpenChat: (bookingId: string) => void; onCancelBooking: (bookingId: string) => void; onConfirmCompletion?: (bookingId: string) => void; }
const compactValue = (value: string, start = 10, end = 8) => value.length > start + end + 3 ? `${value.slice(0, start)}...${value.slice(-end)}` : value;
export const ClientBookingReceipt: React.FC<ClientBookingReceiptProps> = ({ booking, onBack, onOpenChat, onCancelBooking }) => {
  const isDelivered = booking.status === 'Delivered'; const isCompleted = booking.status === 'Completed'; const statusBadge = clientStatusBadge(booking);
  const copy = async (value: string) => { try { await navigator.clipboard.writeText(value); } catch {} };
  return (<div className="max-w-3xl mx-auto pb-28 animate-in fade-in duration-200">
    <div className="flex items-center justify-between gap-3 mb-3"><button type="button" onClick={onBack} className="inline-flex items-center gap-2 px-3 py-1.5 rounded-xl bg-zinc-100 hover:bg-zinc-200 text-zinc-800 text-xs font-black transition"><ArrowLeft className="w-4 h-4" /> My Bookings</button><div className="min-w-0 max-w-[48%] text-right"><ClientAcceptanceBanner booking={booking} compact onOpenChat={onOpenChat} /></div></div>
    <article className="bg-white border border-zinc-200 shadow-sm rounded-sm overflow-hidden">
      <header className="px-4 sm:px-6 pt-4 pb-3 text-center border-b border-dashed border-zinc-300"><div className="w-8 h-8 mx-auto rounded-full bg-zinc-950 text-white flex items-center justify-center mb-1.5"><FileText className="w-4 h-4" /></div><p className="text-[8px] font-black uppercase tracking-[0.22em] text-zinc-400">W3C Pi Bookings</p><p className="text-[10px] text-zinc-500 mt-0.5 truncate">{booking.serviceName}</p></header>
      <section className="px-4 sm:px-6 py-3 border-b border-zinc-200"><div className="grid grid-cols-2 gap-x-4 gap-y-2.5"><div className="min-w-0"><p className="text-[8px] font-black uppercase tracking-wider text-zinc-400">Provider</p><p className="text-sm font-black text-zinc-950 truncate mt-0.5">{booking.providerName || 'Service Provider'}</p>{booking.providerPiUsername && <p className="text-[9px] text-zinc-500 truncate">@{booking.providerPiUsername.replace(/^@+/, '')}</p>}</div><div className="text-right min-w-0"><p className="text-[8px] font-black uppercase tracking-wider text-zinc-400">Status</p><span className={`inline-flex items-center gap-1 mt-0.5 text-[9px] font-extrabold ${statusBadge.classes}`}>{statusBadge.dot && <span className={`w-1.5 h-1.5 rounded-full ${statusBadge.dot}`} />}{statusBadge.label}</span></div><div><p className="text-[8px] font-black uppercase tracking-wider text-zinc-400">Amount Paid</p><p className="text-sm font-black text-zinc-950 mt-0.5">{Number(booking.pricePi || 0).toFixed(2)} π</p></div><div className="text-right"><p className="text-[8px] font-black uppercase tracking-wider text-zinc-400">Payment</p><p className="text-[10px] font-bold text-zinc-900 mt-0.5">{booking.paymentStatus || '—'}</p></div><div><p className="text-[8px] font-black uppercase tracking-wider text-zinc-400">Booked On</p><p className="text-[10px] font-bold text-zinc-900 mt-0.5">{formatBookingCreated(booking.createdAt)}</p></div><div className="text-right"><p className="text-[8px] font-black uppercase tracking-wider text-zinc-400">Booking ID</p><button type="button" onClick={() => copy(booking.id)} className="inline-flex items-center gap-1 text-[10px] font-mono text-zinc-700 mt-0.5 hover:text-amber-700">{compactValue(booking.id)}<Copy className="w-3 h-3 text-zinc-400" /></button></div></div><div className="grid grid-cols-2 gap-4 mt-2.5 pt-2.5 border-t border-zinc-100"><div><p className="text-[8px] font-black uppercase tracking-wider text-zinc-400">Service</p><p className="text-[10px] font-bold text-zinc-900 mt-0.5 truncate">{booking.serviceName}</p></div>{booking.durationMinutes ? <div className="text-right"><p className="text-[8px] font-black uppercase tracking-wider text-zinc-400">Duration</p><p className="text-[10px] font-bold text-zinc-900 mt-0.5">{formatDuration(booking.durationMinutes)}</p></div> : <div />}</div></section>
      {booking.notes && <section className="px-4 sm:px-6 py-3 border-b border-zinc-200"><h2 className="text-[9px] font-black uppercase tracking-[0.16em] text-zinc-500 mb-1.5">Your Project Brief</h2><p className="text-[10px] leading-4 text-zinc-800 whitespace-pre-wrap line-clamp-3">{booking.notes}</p></section>}
      {booking.attachments?.length ? <section className="px-4 sm:px-6 py-3 border-b border-zinc-200"><div className="flex items-center justify-between mb-1.5"><h2 className="text-[9px] font-black uppercase tracking-[0.16em] text-zinc-500">Your Attachments</h2><span className="text-[8px] text-zinc-400">{booking.attachments.length}</span></div><div className="space-y-1">{booking.attachments.slice(0, 3).map(file => <div key={file.id} className="flex items-center gap-2 text-[10px]"><Paperclip className="w-3 h-3 text-amber-600 shrink-0" /><span className="truncate font-medium">{file.name}</span></div>)}{booking.attachments.length > 3 && <p className="text-[9px] text-zinc-400">+{booking.attachments.length - 3} more attachment(s)</p>}</div></section> : null}
      {isDelivered && <section className="px-4 sm:px-6 py-3 border-b border-zinc-200"><h2 className="text-[9px] font-black uppercase tracking-[0.16em] text-zinc-500 mb-1">Delivery</h2><p className="text-[10px] leading-4 text-zinc-700">The provider has marked this service as delivered. Review the delivery before confirming completion.</p>{booking.delivery_notes && <p className="text-[10px] leading-4 mt-1.5 pt-1.5 border-t border-dashed border-zinc-200 line-clamp-2">{booking.delivery_notes}</p>}</section>}
      {booking.piTxHash && <section className="px-4 sm:px-6 py-3 border-b border-zinc-200"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-1.5"><Hash className="w-3.5 h-3.5 text-zinc-500" /><h2 className="text-[9px] font-black uppercase tracking-[0.16em] text-zinc-500">Pi Transaction</h2></div><button type="button" onClick={() => copy(booking.piTxHash!)} className="shrink-0 p-1 rounded-md bg-zinc-50 border border-zinc-200"><Copy className="w-3 h-3" /></button></div><p className="mt-1 font-mono text-[9px] text-zinc-700 truncate">{compactValue(booking.piTxHash, 12, 10)}</p></section>}
      {booking.rejection_reason && <section className="px-4 sm:px-6 py-3 border-b border-zinc-200"><h2 className="text-[9px] font-black uppercase tracking-[0.16em] text-rose-700">Cancellation Reason</h2><p className="text-[10px] leading-4 text-rose-900 mt-1 line-clamp-2">{booking.rejection_reason}</p></section>}
      <footer className="px-4 sm:px-6 py-2.5 text-center"><p className="text-[8px] text-zinc-400">Keep this receipt as a reference for your booking, dispute or appeal.</p></footer>
    </article>
    {isDelivered && <div className="mt-3"><ClientAcceptanceBanner booking={booking} onOpenChat={onOpenChat} /></div>}{!isDelivered && !isCompleted && booking.status === 'Confirmed' && <div className="mt-2 text-center"><button type="button" onClick={() => onCancelBooking(booking.id)} className="text-xs font-semibold text-rose-600 hover:text-rose-700 underline">Request Cancellation & Refund</button></div>}{isDelivered && <div className="mt-2 flex justify-center"><button type="button" onClick={() => onOpenChat(booking.id)} className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-zinc-900 hover:bg-zinc-800 text-white text-xs font-black"><MessageSquare className="w-4 h-4" /> Open Booking Chat</button></div>}
  </div>);
};