import React, { useEffect, useState } from 'react';
import { Provider, SocialLink, ProviderProfileStatus } from '../types';
import { providerService } from '../services/providerService';
import { piAuthService } from '../services/piAuthService';
import { PortfolioUploader } from './media/PortfolioUploader';
import { Save, Plus, Trash2, ArrowLeft } from 'lucide-react';
import { toast } from '../hooks/use-toast';

interface ProviderProfileEditorProps { provider: Provider; onSaved?: (provider: Provider) => void; onBack?: () => void; }
export const ProviderProfileEditor: React.FC<ProviderProfileEditorProps> = ({ provider, onSaved, onBack }) => {
  const [form, setForm] = useState<Provider>(provider);
  const [saving, setSaving] = useState(false);
  const [socialLinks, setSocialLinks] = useState<SocialLink[]>(provider.socialLinks || []);
  const token = piAuthService.getStoredUser()?.accessToken;
  useEffect(() => { setForm(provider); setSocialLinks(provider.socialLinks || []); }, [provider]);
  const set = <K extends keyof Provider>(key: K, value: Provider[K]) => setForm((p) => ({ ...p, [key]: value }));
  const csv = (value: string) => value.split(',').map((v) => v.trim()).filter(Boolean);
  const save = async (e: React.FormEvent) => { e.preventDefault(); setSaving(true); try { const updates = { ...form, socialLinks: socialLinks.filter((s) => s.url.trim()) }; delete (updates as any).photoUrl; delete (updates as any).location; await providerService.updateProvider(form.id, updates, token); const refreshed = await providerService.getProviderByPiUid(form.piUid || ''); const saved = refreshed || { ...form, socialLinks: updates.socialLinks }; onSaved?.(saved); toast({ title: 'Public Profile Updated', description: 'Your provider profile has been saved.' }); } catch (error: any) { toast({ title: 'Save Failed', description: error?.message || 'Could not save your provider profile.', variant: 'destructive' }); } finally { setSaving(false); } };
  const profileStatus: ProviderProfileStatus = form.profileStatus || 'Published';
  const field = 'w-full px-3 py-2 text-xs bg-white border border-zinc-200 rounded-xl focus:outline-none focus:border-amber-500';
  const label = 'text-xs font-semibold text-zinc-700';
  return <div className="space-y-4 pb-24">
    <div className="flex items-center gap-3 border-b border-zinc-200 pb-3"><button type="button" onClick={onBack} className="inline-flex items-center gap-1.5 text-xs font-bold text-zinc-700 hover:text-amber-700"><ArrowLeft className="w-4 h-4" />Back to Provider Console</button><div className="min-w-0"><h2 className="text-lg font-black text-zinc-950">Edit Profile</h2><p className="text-[11px] text-zinc-500">Update the profile clients see.</p></div></div>
    <form onSubmit={save} className="space-y-4">
      <section className="p-4 rounded-2xl bg-zinc-50 border border-zinc-200/80 space-y-3"><h3 className="text-xs font-bold text-zinc-900 uppercase tracking-wide">Profile & Identity</h3><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><label className={label}>Full Name<input required value={form.fullName || ''} onChange={(e) => set('fullName', e.target.value)} placeholder="Full Name" className={field} /></label><label className={label}>Role / Title<input required value={form.roleTitle || ''} onChange={(e) => set('roleTitle', e.target.value)} placeholder="Role / Title" className={field} /></label></div><label className={`${label} block`}>Headline<input value={form.headline || ''} onChange={(e) => set('headline', e.target.value)} placeholder="Headline" className={field} /></label><label className={`${label} block`}>Biography<textarea rows={3} value={form.bio || ''} onChange={(e) => set('bio', e.target.value)} placeholder="Biography / About You" className={field} /></label></section>
      <section className="p-4 rounded-2xl bg-zinc-50 border border-zinc-200/80 space-y-3"><h3 className="text-xs font-bold text-zinc-900 uppercase tracking-wide">Professional Details</h3><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><label className={label}>Specialties<input value={form.specialties?.join(', ') || ''} onChange={(e) => set('specialties', csv(e.target.value))} placeholder="UI/UX, Web Development" className={field} /></label><label className={label}>Skills<input value={form.skills?.join(', ') || ''} onChange={(e) => set('skills', csv(e.target.value))} placeholder="Figma, React, Photoshop" className={field} /></label><label className={label}>Languages<input value={form.languages?.join(', ') || ''} onChange={(e) => set('languages', csv(e.target.value))} placeholder="English, French" className={field} /></label><label className={label}>Years Experience<input type="number" min="0" value={form.yearsExperience ?? ''} onChange={(e) => set('yearsExperience', e.target.value ? Number(e.target.value) : undefined)} placeholder="Years" className={field} /></label><label className={label}>Experience Level<select value={form.experienceLevel || 'Intermediate'} onChange={(e) => set('experienceLevel', e.target.value)} className={field}><option>Entry Level</option><option>Intermediate</option><option>Senior / Expert</option></select></label><label className={label}>Availability<select value={form.availabilityStatus || 'available'} onChange={(e) => set('availabilityStatus', e.target.value)} className={field}><option value="available">Available Now</option><option value="busy">Busy / Limited</option><option value="away">Away</option></select></label><label className={label}>Response Time<input value={form.responseTime || ''} onChange={(e) => set('responseTime', e.target.value)} placeholder="Within 1 hour" className={field} /></label><label className={label}>Service Mode<select value={form.serviceMode || ''} onChange={(e) => set('serviceMode', e.target.value)} className={field}><option value="">Select service mode</option><option value="Remote">Remote / Online</option><option value="Onsite">On-site</option><option value="Hybrid">Hybrid</option></select></label></div></section>
      <section className="p-4 rounded-2xl bg-zinc-50 border border-zinc-200/80 space-y-3"><h3 className="text-xs font-bold text-zinc-900 uppercase tracking-wide">Contact & Profile Links</h3><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><label className={label}>Contact Email<input type="email" value={form.contactEmail || ''} onChange={(e) => set('contactEmail', e.target.value)} placeholder="Email" className={field} /></label><label className={label}>Contact Phone<input value={form.contactPhone || ''} onChange={(e) => set('contactPhone', e.target.value)} placeholder="Phone" className={field} /></label></div><div className="space-y-2 pt-2 border-t border-zinc-200"><div className="flex justify-between items-center"><span className="text-xs font-semibold">Website & Social Links</span><button type="button" onClick={() => setSocialLinks([...socialLinks, { platform: 'Twitter / X', url: '' }])} className="text-xs font-bold text-amber-700 flex items-center gap-1"><Plus className="w-3.5 h-3.5" />Add Link</button></div><input type="url" value={form.website || ''} onChange={(e) => set('website', e.target.value)} placeholder="Website" className={field} />{socialLinks.map((s, i) => <div key={i} className="flex gap-2"><input value={s.platform} onChange={(e) => { const n=[...socialLinks]; n[i]={...n[i],platform:e.target.value}; setSocialLinks(n); }} className="w-1/3 px-3 py-1.5 text-xs bg-white border border-zinc-200 rounded-xl" /><input value={s.url} onChange={(e) => { const n=[...socialLinks]; n[i]={...n[i],url:e.target.value}; setSocialLinks(n); }} className="flex-1 px-3 py-1.5 text-xs bg-white border border-zinc-200 rounded-xl" /><button type="button" onClick={() => setSocialLinks(socialLinks.filter((_,j)=>j!==i))} className="p-1.5 text-zinc-400 hover:text-red-600"><Trash2 className="w-4 h-4" /></button></div>)}</div></section>
      <section className="p-4 rounded-2xl bg-zinc-50 border border-zinc-200/80 space-y-3"><div className="flex items-center justify-between"><h3 className="text-xs font-bold text-zinc-900 uppercase tracking-wide">Portfolio</h3><button type="button" onClick={() => document.getElementById('provider-portfolio-images-input')?.click()} className="w-7 h-7 rounded-full border border-zinc-200 bg-white hover:bg-amber-50 text-amber-700 flex items-center justify-center transition" aria-label="Add portfolio image" title="Add portfolio image"><Plus className="w-4 h-4" /></button></div><PortfolioUploader items={form.portfolioItems || []} onChange={(items) => set('portfolioItems', items)} providerIdentifier={form.id} piAccessToken={token} compact /></section>
      <section className="p-4 rounded-2xl bg-zinc-50 border border-zinc-200/80 space-y-2"><h3 className="text-xs font-bold text-zinc-900 uppercase tracking-wide">Profile Status</h3><select value={profileStatus} onChange={(e) => set('profileStatus', e.target.value as ProviderProfileStatus)} className={field}><option value="Draft">Draft</option><option value="Published">Published</option><option value="Archived">Archived</option></select></section>
      <button type="submit" disabled={saving} className="w-full py-3 rounded-xl bg-gradient-to-r from-amber-500 to-orange-500 text-white font-black text-xs uppercase tracking-wider flex items-center justify-center gap-2 disabled:opacity-50">{saving ? 'Saving Profile...' : <><Save className="w-4 h-4" />Save Public Profile</>}</button>
    </form>
  </div>;
};