import React, { useState } from 'react';
import { Service } from '../types';
import { ArrowLeft, User, ArrowRight, ShieldCheck, AtSign, Send, Mail } from 'lucide-react';
import { BookingProgressBar } from './BookingProgressBar';

interface SelectDetailsStepProps {
  service: Service;
  initialDetails: { clientName: string; clientPiUsername: string; clientPhone: string; clientEmail?: string; notes: string };
  onBack: () => void;
  onProceedToSchedule: (details: { clientName: string; clientPiUsername: string; clientPhone: string; clientEmail: string; notes: string }) => void;
}

export const SelectDetailsStep: React.FC<SelectDetailsStepProps> = ({ service, initialDetails, onBack, onProceedToSchedule }) => {
  const [clientName, setClientName] = useState(initialDetails.clientName || '');
  const [rawUsername, setRawUsername] = useState(() => initialDetails.clientPiUsername ? initialDetails.clientPiUsername.replace(/^@+/, '') : '');
  const [clientPhone, setClientPhone] = useState(initialDetails.clientPhone || '');
  const [clientEmail, setClientEmail] = useState(initialDetails.clientEmail || '');
  const [notes, setNotes] = useState(initialDetails.notes || '');
  const handleSubmit = (e: React.FormEvent) => { e.preventDefault(); const finalHandle = rawUsername ? `@${rawUsername.replace(/^@+/, '')}` : (initialDetails.clientPiUsername || ''); onProceedToSchedule({ clientName: clientName.trim(), clientPiUsername: finalHandle, clientPhone: clientPhone.trim(), clientEmail: clientEmail.trim(), notes }); };
  return (
    <div className="max-w-md mx-auto space-y-4 pb-28 animate-in fade-in duration-200">
      <BookingProgressBar currentStep={1} />
      <div className="flex items-center justify-between"><button type="button" onClick={onBack} id="btn-back-to-service-detail" className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-zinc-100 text-zinc-800 text-xs font-bold hover:bg-zinc-200 transition cursor-pointer"><ArrowLeft className="w-3.5 h-3.5" /><span>Service Details</span></button><span className="text-xs font-bold px-2.5 py-1 rounded-full bg-amber-50 text-amber-700 border border-amber-200/80">Step 1: Contact & Brief</span></div>
      <div className="p-4 rounded-3xl bg-amber-500/10 shadow-md flex items-center justify-between gap-3"><div className="min-w-0"><span className="text-[10px] font-extrabold uppercase tracking-wider text-amber-900 block">Selected Service</span><h2 className="text-sm font-black text-zinc-900 truncate">{service.name}</h2><span className="text-xs text-zinc-600 font-medium">{service.durationMinutes} mins duration</span></div><div className="text-right shrink-0"><span className="text-lg font-black text-amber-600">{service.pricePi} π</span></div></div>
      <form onSubmit={handleSubmit} className="space-y-4">
        <div className="p-5 rounded-3xl bg-white shadow-md space-y-4"><h3 className="text-xs font-bold text-zinc-600 uppercase tracking-wider">1. Client Contact Details</h3><div className="space-y-3">
          <div><label className="block text-[11px] font-bold text-zinc-700 mb-1">Full Name</label><div className="relative"><User className="w-4 h-4 text-[#e17100] absolute left-3.5 top-3" /><input type="text" required value={clientName} onChange={(e) => setClientName(e.target.value)} placeholder="e.g. Adeyemo Jibola" className="w-full pl-10 pr-4 py-2.5 rounded-2xl bg-zinc-50 focus:bg-white text-xs text-zinc-900 placeholder-zinc-400 focus:outline-none focus:ring-2 focus:ring-amber-500/30 transition shadow-2xs" /></div></div>
          <div><label className="block text-[11px] font-bold text-zinc-700 mb-1">Pi Network Username</label><div className="relative flex items-center"><div className="absolute left-3.5 text-amber-600 font-bold text-xs pointer-events-none"><AtSign className="w-3.5 h-3.5" /></div><input type="text" required value={rawUsername} onChange={(e) => setRawUsername(e.target.value.replace(/^@+/, ''))} onBlur={() => setRawUsername(rawUsername.replace(/^@+/, ''))} placeholder="pi_pioneer_2749" className="w-full pl-9 pr-4 py-2.5 rounded-2xl bg-zinc-50 focus:bg-white text-xs text-zinc-900 placeholder-zinc-400 focus:outline-none focus:ring-2 focus:ring-amber-500/30 transition shadow-2xs" /></div><p className="text-[10px] text-zinc-500 mt-1">Your verified Pi handle for order tracking: <span className="text-amber-700 font-mono font-bold">@{rawUsername.replace(/^@+/, '') || 'pi_user'}</span></p></div>
          <div><label className="block text-[11px] font-bold text-zinc-700 mb-1">Telegram Username <span className="font-normal text-zinc-400">(optional)</span></label><div className="relative flex items-center"><div className="absolute left-3.5 text-amber-600 font-bold text-xs pointer-events-none"><Send className="w-3.5 h-3.5" /></div><input type="text" value={clientPhone} onChange={(e) => setClientPhone(e.target.value)} placeholder="@telegram_handle" className="w-full pl-9 pr-4 py-2.5 rounded-2xl bg-zinc-50 focus:bg-white text-xs text-zinc-900 placeholder-zinc-400 focus:outline-none focus:ring-2 focus:ring-amber-500/30 transition shadow-2xs" /></div><p className="text-[10px] text-zinc-500 mt-1">Used for booking communication when available.</p></div>
          <div><label className="block text-[11px] font-bold text-zinc-700 mb-1">Email Address</label><div className="relative flex items-center"><div className="absolute left-3.5 text-amber-600 font-bold text-xs pointer-events-none"><Mail className="w-3.5 h-3.5" /></div><input type="email" required value={clientEmail} onChange={(e) => setClientEmail(e.target.value)} placeholder="you@example.com" className="w-full pl-9 pr-4 py-2.5 rounded-2xl bg-zinc-50 focus:bg-white text-xs text-zinc-900 placeholder-zinc-400 focus:outline-none focus:ring-2 focus:ring-amber-500/30 transition shadow-2xs" /></div><p className="text-[10px] text-zinc-500 mt-1">A reliable contact method for your provider and booking updates.</p></div>
        </div></div>
        <div className="p-5 rounded-3xl bg-white shadow-md space-y-4"><h3 className="text-xs font-bold text-zinc-600 uppercase tracking-wider">2. Project Brief</h3><div><label className="block text-[11px] font-bold text-zinc-700 mb-1">Appointment Notes / Requirements Brief</label><textarea rows={5} value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Describe your goals, reference links, specific requirements or questions..." className="w-full p-3 rounded-2xl bg-zinc-50 focus:bg-white text-xs text-zinc-900 placeholder-zinc-400 focus:outline-none focus:ring-2 focus:ring-amber-500/30 transition shadow-2xs whitespace-pre-wrap" /></div></div>
        <div className="p-3.5 rounded-2xl bg-emerald-50 shadow-2xs flex items-center gap-2.5 text-xs text-emerald-900 font-medium"><ShieldCheck className="w-4 h-4 text-emerald-600 shrink-0" /><span>Your booking & brief are protected by Pi Network Merchant Security.</span></div>
        <div className="fixed bottom-0 left-0 right-0 p-3.5 bg-white/95 backdrop-blur-md border-t border-zinc-200 z-50 shadow-lg"><div className="max-w-md mx-auto flex items-center justify-between gap-3"><div className="text-xs"><span className="block text-zinc-400 font-bold text-[10px]">STEP 1 OF 4</span><span className="font-bold text-zinc-900">Details & Brief</span></div><button type="submit" id="btn-proceed-to-schedule" className="flex-1 py-3.5 px-5 rounded-2xl bg-amber-600 hover:bg-amber-500 text-white font-black text-sm active:scale-[0.98] transition flex items-center justify-center gap-2 min-h-[48px] shadow-md shadow-amber-600/20 cursor-pointer"><span>Next: Select Date</span><ArrowRight className="w-4 h-4 stroke-[2.5]" /></button></div></div>
      </form>
    </div>
  );
};