import React, { useEffect, useMemo, useState } from 'react';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import { Service, BusinessProfile, Provider } from '../types';
import { MerchantCard } from './MerchantCard';
import { providerService } from '../services/providerService';
import { categoryService, ServiceCategory } from '../services/categoryService';
import { formatDuration } from '../lib/formatDuration';
import { usePiAuth } from '../hooks/usePiAuth';
import { PiWatermark } from './PiWatermark';

interface ServiceBrowserProps { business: BusinessProfile; services?: Service[]; onSelectService?: (service: Service) => void; onOpenAbout: (merchant?: BusinessProfile | Provider) => void; onOpenSearch?: (query?: string, category?: string) => void; }
type HeroSlide = { eyebrow: string; title: string; description: string; cta: string; action: 'services' | 'providers' | 'become' };
const HERO_SLIDES: HeroSlide[] = [
  { eyebrow: 'W3C Digital Network', title: 'Find what you need — or who can provide it.', description: 'Discover bookable digital services and verified Pi Network providers in one marketplace.', cta: 'Explore Services', action: 'services' },
  { eyebrow: 'How W3C Pi Bookings Works', title: 'Discover. Book. Work together.', description: 'Find a service, review the provider, and start a booking through the existing W3C flow.', cta: 'Browse Services', action: 'services' },
  { eyebrow: 'For Providers', title: 'Put your skills in front of clients.', description: 'Build your provider presence and offer services through the W3C marketplace.', cta: 'Become a Provider', action: 'become' },
  { eyebrow: 'Meet the Community', title: 'Search for the right provider directly.', description: 'Switch to Providers to explore people by role, skills, specialties, ratings, and more.', cta: 'Find Providers', action: 'providers' },
];

export const ServiceBrowser: React.FC<ServiceBrowserProps> = ({ business, services = [], onSelectService, onOpenAbout, onOpenSearch }) => {
  const { piUser, signIn } = usePiAuth();
  const [providers, setProviders] = useState<Provider[]>(() => providerService.getProvidersLocal());
  const [categories, setCategories] = useState<ServiceCategory[]>([]);
  const [slideIndex, setSlideIndex] = useState(0);
  useEffect(() => { let isMounted = true; providerService.getProvidersAsync().then((data) => { if (isMounted && data) setProviders(data); }); return () => { isMounted = false; }; }, []);
  useEffect(() => { let isMounted = true; categoryService.listActive().then((data) => { if (isMounted) setCategories(data); }).catch(() => { if (isMounted) setCategories([]); }); return () => { isMounted = false; }; }, []);
  useEffect(() => { const timer = window.setInterval(() => setSlideIndex((current) => (current + 1) % HERO_SLIDES.length), 6500); return () => window.clearInterval(timer); }, []);
  const requireSignIn = (action: () => void) => { if (piUser) action(); else signIn(); };
  const publicProviders = providers.filter((p) => p.status === 'Approved' && (p.profileStatus || 'Published') === 'Published' && p.profileVisibility !== 'private');
  const topProviders = publicProviders.slice(0, 4); const risingProviders = publicProviders.length > 4 ? publicProviders.slice(4) : [];
  const publishedServices = services.filter((s) => s.status === 'Published');
  const featuredCategories = useMemo(() => { const featured = categories.filter((category) => category.isFeatured); return featured.length ? featured : categories; }, [categories]);
  const currentSlide = HERO_SLIDES[slideIndex];
  const handleCategoryClick = (categorySlug: string) => { if (onOpenSearch) onOpenSearch('', categorySlug); };
  const openAllProviders = () => { if (onOpenSearch) onOpenSearch('__providers__'); };
  const handleHeroAction = () => { if (currentSlide.action === 'services') onOpenSearch?.(''); else if (currentSlide.action === 'providers') onOpenSearch?.('__providers__'); else onOpenSearch?.('__become_provider__'); };
  return <div className="w-full space-y-8 pb-12 animate-in fade-in duration-200">
    <section className="relative h-[260px] sm:h-[230px] overflow-hidden rounded-3xl bg-gradient-to-br from-orange-600 via-orange-500 to-amber-600 text-white shadow-lg"><PiWatermark variant="dark-hero" /><div className="relative z-10 h-full min-h-0 p-6 sm:p-8 flex flex-col justify-center gap-4 sm:gap-5"><div className="w-full max-w-2xl mr-auto space-y-2 text-left"><div className="text-[clamp(9px,2vw,11px)] font-extrabold uppercase tracking-[0.18em] text-orange-100">{currentSlide.eyebrow}</div><h1 className="text-[clamp(24px,5vw,34px)] font-black tracking-tight leading-[1.08]">{currentSlide.title}</h1><p className="max-w-xl text-[clamp(12px,2.2vw,15px)] text-orange-50/90 font-medium leading-relaxed">{currentSlide.description}</p></div><div className="w-full flex items-center justify-between gap-3"><button type="button" onClick={handleHeroAction} className="shrink-0 rounded-xl bg-white px-4 py-2.5 text-xs font-black text-orange-700 shadow-sm hover:bg-orange-50 transition">{currentSlide.cta}</button><div className="flex items-center gap-1.5 shrink-0"><button type="button" aria-label="Previous slide" onClick={() => setSlideIndex((slideIndex - 1 + HERO_SLIDES.length) % HERO_SLIDES.length)} className="p-2 rounded-full bg-white/15 hover:bg-white/25 transition"><ChevronLeft className="w-4 h-4" /></button>{HERO_SLIDES.map((_, index) => <button key={index} type="button" aria-label={`Go to slide ${index + 1}`} onClick={() => setSlideIndex(index)} className={`h-1.5 rounded-full transition-all ${index === slideIndex ? 'w-6 bg-white' : 'w-1.5 bg-white/45'}`} />)}<button type="button" aria-label="Next slide" onClick={() => setSlideIndex((slideIndex + 1) % HERO_SLIDES.length)} className="p-2 rounded-full bg-white/15 hover:bg-white/25 transition"><ChevronRight className="w-4 h-4" /></button></div></div></div></section>
    <div className="w-full space-y-3"><div className="flex items-center justify-between gap-2 px-1 text-left"><div><h2 className="text-xs font-black uppercase tracking-wider text-zinc-500">Explore Categories</h2><p className="text-[11px] text-zinc-400 mt-1">Browse services by what you need.</p></div><button type="button" onClick={() => onOpenSearch?.('')} className="text-[11px] font-black text-orange-600 hover:text-orange-700">View all</button></div><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-2">{featuredCategories.map((cat) => <button key={cat.id} type="button" onClick={() => handleCategoryClick(cat.slug)} id={`cat-btn-${cat.slug}`} className="min-h-12 px-3 py-2 rounded-xl bg-amber-500/90 hover:bg-amber-400 shadow-xs hover:shadow-sm transition active:scale-[0.98] cursor-pointer flex items-center justify-center text-center"><span className="text-xs font-black text-white tracking-tight leading-snug">{cat.name}</span></button>)}</div></div>
    {publishedServices.length > 0 && <div className="w-full space-y-4"><div className="flex items-center justify-between gap-2 px-1 text-left"><h2 className="text-base font-black text-zinc-900 tracking-tight">Popular Service</h2><button type="button" onClick={() => onOpenSearch?.('')} className="text-xs font-black text-orange-600 hover:text-orange-700 cursor-pointer">View All Services →</button></div><div className="w-full flex gap-4 overflow-x-auto pb-4 pt-1 px-1 snap-x snap-mandatory scrollbar-none justify-start sm:justify-start">{publishedServices.slice(0, 4).map((service) => <div key={service.id} onClick={() => requireSignIn(() => onSelectService?.(service))} id={`home-service-card-${service.id}`} className="group w-[280px] sm:w-[330px] shrink-0 snap-center sm:snap-start p-4 rounded-2xl bg-zinc-50 shadow-xs hover:shadow-sm hover:bg-orange-50/60 transition-all cursor-pointer flex flex-col justify-between space-y-3 border border-zinc-100/60"><div className="space-y-2"><div className="flex items-center justify-between gap-2"><span className="inline-block px-3 py-1 rounded-full bg-orange-100/70 text-orange-950 text-[10px] font-extrabold uppercase tracking-wider">{service.categoryName || String(service.category || 'Uncategorized').replace(/_/g, ' ')}</span><span className="text-[11px] text-zinc-500 font-bold">{formatDuration(service.durationMinutes, service.durationValue, service.durationUnit)}</span></div><h3 className="font-extrabold text-sm sm:text-base text-zinc-900 group-hover:text-orange-600 transition line-clamp-2 text-left">{service.name}</h3>{service.description && <p className="text-xs text-zinc-600 line-clamp-2 leading-relaxed font-normal text-left">{service.description}</p>}</div><div className="pt-3 border-t border-zinc-200 flex items-center justify-between"><div><span className="text-[10px] font-extrabold text-zinc-400 uppercase tracking-wider block">Price</span><span className="text-lg font-black text-orange-600 tracking-tight">{service.pricePi} <span className="text-xs font-bold text-orange-500">π</span></span></div><button type="button" onClick={(event) => { event.stopPropagation(); requireSignIn(() => onSelectService?.(service)); }} className="px-4 py-2 rounded-xl bg-orange-600 hover:bg-orange-500 text-white font-black text-xs transition cursor-pointer shadow-xs">Book Service</button></div></div>)}</div></div>}
    <div className="w-full space-y-4"><div className="flex items-center justify-between gap-2 px-1 text-left"><h2 className="text-base font-black text-zinc-900 tracking-tight">Top Service Providers</h2><button type="button" onClick={openAllProviders} className="text-xs font-black text-orange-600 hover:text-orange-700 cursor-pointer">View All Providers →</button></div><div className="w-full flex gap-4 overflow-x-auto pb-4 pt-1 px-1 snap-x snap-mandatory scrollbar-none justify-start sm:justify-start">{topProviders.map((provider) => <MerchantCard key={provider.id} merchant={provider} services={publishedServices} onOpenAbout={(merchant) => requireSignIn(() => onOpenAbout(merchant))} className="w-[280px] sm:w-[330px] shrink-0 snap-center sm:snap-start" />)}</div></div>
    {risingProviders.length > 0 && <div className="w-full space-y-4"><div className="flex flex-col sm:flex-row items-center justify-between text-center sm:text-left gap-2 px-1"><div><h2 className="text-base font-black text-zinc-900 tracking-tight">Rising Professionals</h2><p className="text-xs text-zinc-500 font-medium">Emerging talent and specialists in the community</p></div></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{risingProviders.map((provider) => <MerchantCard key={provider.id} merchant={provider} services={publishedServices} onOpenAbout={(merchant) => requireSignIn(() => onOpenAbout(merchant))} />)}</div></div>}
  </div>;
};