import React, { useEffect, useMemo, useState } from 'react';
import { ShieldCheck } from 'lucide-react';
import { Service, BusinessProfile, Provider } from '../types';
import { MerchantCard } from './MerchantCard';
import { providerService } from '../services/providerService';
import { categoryService, ServiceCategory } from '../services/categoryService';
import { CategoryIcon } from './CategoryIcon';
import { formatDuration } from '../lib/formatDuration';
import { usePiAuth } from '../hooks/usePiAuth';
interface ServiceBrowserProps { business: BusinessProfile; services?: Service[]; onSelectService?: (service: Service) => void; onOpenAbout: (merchant?: BusinessProfile | Provider) => void; onOpenSearch?: (query?: string, category?: string) => void; }
export const ServiceBrowser: React.FC<ServiceBrowserProps> = ({ business, services = [], onSelectService, onOpenAbout, onOpenSearch }) => {
  const { piUser, signIn } = usePiAuth();
  const [providers, setProviders] = useState<Provider[]>(() => providerService.getProvidersLocal());
  const [categories, setCategories] = useState<ServiceCategory[]>([]);
  useEffect(() => { let isMounted = true; providerService.getProvidersAsync().then((data) => { if (isMounted && data) setProviders(data); }); return () => { isMounted = false; }; }, []);
  useEffect(() => { let isMounted = true; categoryService.listActive().then((data) => { if (isMounted) setCategories(data); }).catch(() => { if (isMounted) setCategories([]); }); return () => { isMounted = false; }; }, []);
  const requireSignIn = (action: () => void) => { if (piUser) action(); else signIn(); };
  const publicProviders = providers.filter((p) => p.status === 'Approved' && (p.profileStatus || 'Published') === 'Published' && p.profileVisibility !== 'private'); const topProviders = publicProviders.slice(0, 4); const risingProviders = publicProviders.length > 4 ? publicProviders.slice(4) : []; const publishedServices = services.filter((s) => s.status === 'Published');
  const featuredCategories = useMemo(() => { const featured = categories.filter((category) => category.isFeatured); return featured.length ? featured : categories; }, [categories]);
  const handleCategoryClick = (categorySlug: string) => { if (onOpenSearch) onOpenSearch('', categorySlug); }; const openAllProviders = () => { if (onOpenSearch) onOpenSearch('__providers__'); };
  return <div className="w-full space-y-8 pb-12 animate-in fade-in duration-200">
    <div className="relative w-full rounded-3xl overflow-hidden bg-hero-gradient text-white p-6 sm:p-10 shadow-lg text-left flex flex-col items-start justify-center"><div className="relative z-10 max-w-xl mx-0 space-y-3 flex flex-col items-start text-left"><div className="inline-block px-3 py-1 rounded-full bg-white/20 backdrop-blur-md text-[11px] font-extrabold uppercase tracking-widest text-orange-50">W3C Service Marketplace</div><h1 className="text-2xl sm:text-4xl font-black tracking-tight leading-tight text-left">Find & book expert digital services natively with Pi</h1><p className="text-xs sm:text-sm text-orange-100 leading-relaxed font-medium text-left">Connect with verified Web3 developers, UI/UX designers, and digital professionals. Secure bookings with smart Pi Escrow protection.</p></div></div>
    <div className="w-full space-y-3"><div className="flex items-center justify-between gap-2 px-1 text-left"><div><h2 className="text-xs font-black uppercase tracking-wider text-zinc-500">Explore Categories</h2><p className="text-[11px] text-zinc-400 mt-1">Browse services by what you need.</p></div><button type="button" onClick={() => onOpenSearch?.('')} className="text-[11px] font-black text-orange-600 hover:text-orange-700">View all</button></div><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">{featuredCategories.map((cat) => <button key={cat.id} onClick={() => handleCategoryClick(cat.slug)} id={`cat-btn-${cat.slug}`} className="p-4 rounded-2xl bg-zinc-50 hover:bg-orange-50/60 shadow-xs hover:shadow-sm transition text-left space-y-3 active:scale-95 cursor-pointer flex flex-col items-start justify-center"><span className="w-9 h-9 rounded-xl bg-orange-100 text-orange-700 flex items-center justify-center"><CategoryIcon icon={cat.icon} className="w-4 h-4" /></span><span className="text-xs font-black text-zinc-900 block tracking-tight">{cat.name}</span>{cat.description && <span className="text-[10px] leading-relaxed font-medium text-zinc-500 line-clamp-2">{cat.description}</span>}<span className="text-[10px] font-black text-orange-600">Browse listings →</span></button>)}</div></div>
    <div className="w-full space-y-4"><div className="flex flex-col sm:flex-row items-center justify-between text-center sm:text-left gap-2 px-1"><div><h2 className="text-base font-black text-zinc-900 tracking-tight">Top Service Providers</h2><p className="text-xs text-zinc-500 font-medium">Verified professionals and team leads on the W3C network</p></div></div><div className="w-full flex gap-4 overflow-x-auto pb-4 pt-1 px-1 snap-x snap-mandatory scrollbar-none justify-start sm:justify-start">{topProviders.map((provider) => <MerchantCard key={provider.id} merchant={provider} services={publishedServices} onOpenAbout={(merchant) => requireSignIn(() => onOpenAbout(merchant))} className="w-[280px] sm:w-[330px] shrink-0 snap-center sm:snap-start" />)}</div><div className="flex justify-center pt-1"><button onClick={openAllProviders} className="text-xs font-black text-orange-600 hover:text-orange-700 cursor-pointer">View All Providers →</button></div></div>
    {publishedServices.length > 0 && <div className="w-full space-y-4"><div className="flex flex-col items-center text-center px-1"><h2 className="text-base font-black text-zinc-900 tracking-tight">Popular Service</h2><p className="text-xs text-zinc-500 font-medium">Fixed-scope digital services ready for direct booking</p></div><div className="w-full flex gap-4 overflow-x-auto pb-4 pt-1 px-1 snap-x snap-mandatory scrollbar-none justify-start sm:justify-start">{publishedServices.slice(0, 4).map((service) => <div key={service.id} onClick={() => requireSignIn(() => onSelectService?.(service))} id={`home-service-card-${service.id}`} className="group w-[280px] sm:w-[330px] shrink-0 snap-center sm:snap-start p-4 rounded-2xl bg-zinc-50 shadow-xs hover:shadow-sm hover:bg-orange-50/60 transition-all cursor-pointer flex flex-col justify-between space-y-3 border border-zinc-100/60"><div className="space-y-2"><div className="flex items-center justify-between gap-2"><span className="inline-block px-3 py-1 rounded-full bg-orange-100/70 text-orange-950 text-[10px] font-extrabold uppercase tracking-wider">{service.categoryName || String(service.category || 'Uncategorized').replace(/_/g, ' ')}</span><span className="text-[11px] text-zinc-500 font-bold">{formatDuration(service.durationMinutes, service.durationValue, service.durationUnit)}</span></div><h3 className="font-extrabold text-sm sm:text-base text-zinc-900 group-hover:text-orange-600 transition line-clamp-2 text-left">{service.name}</h3>{service.description && <p className="text-xs text-zinc-600 line-clamp-2 leading-relaxed font-normal text-left">{service.description}</p>}</div><div className="pt-3 border-t border-zinc-200 flex items-center justify-between"><div><span className="text-[10px] font-extrabold text-zinc-400 uppercase tracking-wider block">Price</span><span className="text-lg font-black text-orange-600 tracking-tight">{service.pricePi} <span className="text-xs font-bold text-orange-500">π</span></span></div><button type="button" onClick={(event) => { event.stopPropagation(); requireSignIn(() => onSelectService?.(service)); }} className="px-4 py-2 rounded-xl bg-orange-600 hover:bg-orange-500 text-white font-black text-xs transition cursor-pointer shadow-xs">Book Service</button></div></div>)}</div><div className="flex justify-center pt-1"><button onClick={() => onOpenSearch && onOpenSearch('')} className="text-xs font-black text-orange-600 hover:text-orange-700 cursor-pointer">View All Services →</button></div></div>}
    {risingProviders.length > 0 && <div className="w-full space-y-4"><div className="flex flex-col sm:flex-row items-center justify-between text-center sm:text-left gap-2 px-1"><div><h2 className="text-base font-black text-zinc-900 tracking-tight">Rising Professionals</h2><p className="text-xs text-zinc-500 font-medium">Emerging talent and specialists in the community</p></div></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{risingProviders.map((provider) => <MerchantCard key={provider.id} merchant={provider} services={publishedServices} onOpenAbout={(merchant) => requireSignIn(() => onOpenAbout(merchant))} />)}</div></div>}
    <div className="w-full p-6 sm:p-7 rounded-3xl bg-zinc-900 text-white space-y-3 shadow-md border border-zinc-800"><div className="flex items-center gap-2 text-amber-400"><ShieldCheck className="w-5 h-5 shrink-0" /><h2 className="text-sm font-black uppercase tracking-wider">Testnet Safety Notice</h2></div><p className="text-xs text-zinc-300 leading-relaxed font-normal">W3C Pi Bookings is currently operating on Pi Testnet for testing and development. Transactions and balances in this environment are not Mainnet transactions.</p><p className="text-xs text-zinc-400 leading-relaxed font-normal">Use the Pi Wallet you intend to use for testing and treat your wallet credentials with the same level of security you would use on Mainnet. <strong className="text-white font-bold">Never share your passphrase, private key, or wallet credentials with this application or anyone else.</strong></p></div>
  </div>;
};
