import { Service } from '../types';
import { supabase, isSupabaseConfigured } from '../lib/supabase';
const LOCAL_SERVICES_KEY = 'w3c_services';
function logRLSHint(tableName: string) { console.warn(`[Supabase RLS Warning] Operation on table '${tableName}' was blocked by Row Level Security.`); }
export const serviceService = {
  getServicesLocal(): Service[] { const cached = localStorage.getItem(LOCAL_SERVICES_KEY); if (!cached) return []; try { return JSON.parse(cached); } catch { return []; } },
  async getServicesAsync(): Promise<Service[]> { const localServices = this.getServicesLocal(); if (!isSupabaseConfigured()) return localServices; try { const { data, error } = await supabase.from('services').select('*, providers(*)').order('created_at', { ascending: true }); if (error) { console.warn('[Supabase Note] Failed to fetch services:', error.message); if (error.code === '42501') logRLSHint('services'); return localServices; } if (!data || data.length === 0) { localStorage.setItem(LOCAL_SERVICES_KEY, JSON.stringify([])); return []; } const remoteServices: Service[] = data.map((row: any) => ({ id: row.id, name: row.title || 'Untitled Service', category: row.category || 'web_dev', description: row.short_description || '', coverImageUrl: row.cover_image || '', included: Array.isArray(row.deliverables) ? row.deliverables : [], durationMinutes: Number(row.duration) || 60, durationValue: Number(row.duration_value) || Number(row.duration) || 60, durationUnit: row.duration_unit || 'minutes', basePrice: Number(row.base_price) || Number(row.base_price_ngn) || 0, currency: String(row.base_currency || 'NGN').toUpperCase(), priceNGN: Number(row.base_price_ngn) || (String(row.base_currency || 'NGN').toUpperCase() === 'NGN' ? Number(row.base_price) || 0 : 0), pricePi: Number(row.calculated_pi_price) || 0, featured: row.featured ?? false, providerName: row.provider_name || '', providerRole: row.provider_role || '', providerId: row.provider_id || undefined, provider: row.providers ? { id: row.providers.id, fullName: row.providers.full_name, piUsername: row.providers.pi_username, piWalletAddress: row.providers.pi_wallet_address, roleTitle: row.providers.role_title, photoUrl: row.providers.photo_url, contactEmail: row.providers.contact_email, contactPhone: row.providers.contact_phone, status: row.providers.status } : undefined, locationType: row.location_type || 'Online / Remote', status: row.status || 'Published', createdAt: row.created_at, updatedAt: row.updated_at })); localStorage.setItem(LOCAL_SERVICES_KEY, JSON.stringify(remoteServices)); return remoteServices; } catch (e: any) { console.error('[Supabase Exception] Error fetching services:', e?.message || e); return localServices; } },
  async addService(service: Omit<Service, 'id'>): Promise<Service> { throw new Error('Legacy service creation is disabled. Provider services must use the Pi API.'); },
  async updateService(_serviceId: string, _updates: Partial<Service>): Promise<Service[]> { throw new Error('Legacy service editing is disabled. Provider services must use the Pi API.'); },
  async deleteService(_serviceId: string): Promise<Service[]> { throw new Error('Legacy service deletion is disabled.'); },
};