import React, { useRef, useState } from 'react';
import { Plus, Trash2, Loader2, AlertCircle, Image as ImageIcon, MessageSquare, X } from 'lucide-react';
import { providerMediaService, getMediaUrl, validateMediaFile } from '../../services/providerMediaService';
import { PortfolioItem } from '../../types';
export interface PortfolioUploaderProps { items: PortfolioItem[]; onChange: (items: PortfolioItem[]) => void; providerIdentifier: string; piAccessToken?: string; className?: string; disabled?: boolean; maxItems?: number; compact?: boolean; }
interface UploadingState { id: string; fileName: string; previewUrl: string; progress: boolean; error?: string; }
export const PortfolioUploader: React.FC<PortfolioUploaderProps> = ({ items = [], onChange, providerIdentifier, piAccessToken, className = '', disabled = false, maxItems = 12, compact = false }) => {
 const fileInputRef=useRef<HTMLInputElement|null>(null); const [uploadingQueue,setUploadingQueue]=useState<UploadingState[]>([]); const [generalError,setGeneralError]=useState(''); const handleOpenPicker=()=>{if(disabled)return;setGeneralError('');fileInputRef.current?.click()};
 const handleFilesSelected=async(e:React.ChangeEvent<HTMLInputElement>)=>{const fileList=e.target.files;if(!fileList?.length)return;const selectedFiles=Array.from(fileList);if(fileInputRef.current)fileInputRef.current.value='';if(items.length+selectedFiles.length>maxItems){setGeneralError(`You can upload a maximum of ${maxItems} portfolio images.`);return;}for(const file of selectedFiles){const validation=validateMediaFile(file);if(!validation.valid){setGeneralError(`"${file.name}": ${validation.error}`);continue;}const tempId=`temp_${Date.now()}_${Math.random().toString(36).substring(2,8)}`;const localBlobUrl=URL.createObjectURL(file);setUploadingQueue(p=>[...p,{id:tempId,fileName:file.name,previewUrl:localBlobUrl,progress:true}]);try{const result=await providerMediaService.uploadPortfolioImage(file,{providerIdentifier:providerIdentifier||'provider',piAccessToken});const newItem:PortfolioItem={id:tempId,imageUrl:result.publicUrl||localBlobUrl,path:result.path,caption:''};setUploadingQueue(p=>p.filter(q=>q.id!==tempId));onChange([...items,newItem]);}catch(err:any){console.error('Portfolio upload error:',err);setUploadingQueue(p=>p.map(q=>q.id===tempId?{...q,progress:false,error:err?.message||'Upload failed'}:q));}}};
 const handleRemoveItem=(index:number)=>{if(!disabled)onChange(items.filter((_,idx)=>idx!==index))}; const handleUpdateCaption=(index:number,caption:string)=>onChange(items.map((item,idx)=>idx===index?{...item,caption}:item)); const dismiss=(id:string)=>setUploadingQueue(p=>p.filter(q=>q.id!==id));
 return <div className={`space-y-3 ${className}`}><input ref={fileInputRef} type="file" multiple accept="image/png,image/jpeg,image/jpg,image/webp" onChange={handleFilesSelected} disabled={disabled} className="hidden" id="provider-portfolio-images-input" aria-label="Upload portfolio images" />{generalError&&<div className="p-3 rounded-xl bg-rose-50 border border-rose-200 flex items-start justify-between gap-2 text-xs text-rose-700 font-medium"><div className="flex items-center gap-2"><AlertCircle className="w-4 h-4"/><span>{generalError}</span></div><button type="button" onClick={()=>setGeneralError('')}><X className="w-3.5 h-3.5"/></button></div>}
 <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">{items.map((item,index)=>{const displayUrl=getMediaUrl(item.imageUrl||item.path);return <div key={item.id||`portfolio_${index}`} className="group relative rounded-2xl bg-zinc-50 border border-zinc-200 overflow-hidden"><div className="relative aspect-4/3 bg-zinc-900 overflow-hidden"><img src={displayUrl} alt={item.caption||`Portfolio work ${index+1}`} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"/><button type="button" onClick={()=>handleRemoveItem(index)} disabled={disabled} className="absolute top-2 right-2 p-1.5 rounded-full bg-zinc-950/75 hover:bg-rose-600 text-white"><Trash2 className="w-3.5 h-3.5"/></button></div><div className="p-3 bg-white space-y-1.5"><label className="text-[10px] font-extrabold text-zinc-500 uppercase tracking-wider block">Caption / Description</label><input type="text" value={item.caption||''} onChange={e=>handleUpdateCaption(index,e.target.value)} disabled={disabled} placeholder="Describe this work" className="w-full px-2.5 py-1.5 rounded-lg bg-zinc-50 border border-zinc-200 text-xs focus:outline-none focus:border-amber-500"/></div></div>})}
 {uploadingQueue.map(q=><div key={q.id} className="relative rounded-2xl bg-zinc-50 border border-zinc-200 overflow-hidden"><div className="relative aspect-4/3 bg-zinc-900"><img src={q.previewUrl} alt={q.fileName} className="w-full h-full object-cover opacity-60"/><div className="absolute inset-0 bg-black/60 flex flex-col items-center justify-center text-white text-center p-3">{q.progress?<><Loader2 className="w-6 h-6 animate-spin mb-1.5"/><span className="text-xs font-bold">Uploading...</span></>:<><AlertCircle className="w-6 h-6 text-rose-400"/><span className="text-xs font-bold">Upload Failed</span><button type="button" onClick={()=>dismiss(q.id)} className="mt-2 text-[10px] font-bold">Dismiss</button></>}</div></div></div>)}
 {items.length+uploadingQueue.length<maxItems&&!compact&&<div role="button" tabIndex={0} onClick={handleOpenPicker} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();handleOpenPicker()}}} className="group rounded-2xl border-2 border-dashed border-zinc-300 hover:border-amber-500 bg-zinc-50 hover:bg-amber-50/30 min-h-[160px] flex flex-col items-center justify-center p-5 text-center cursor-pointer"><div className="w-10 h-10 rounded-full bg-zinc-200/70 group-hover:bg-amber-100 flex items-center justify-center mb-2 text-zinc-600 group-hover:text-amber-600"><Plus className="w-5 h-5"/></div><span className="text-xs font-black">Add Portfolio Image</span><span className="text-[10px] text-zinc-500 mt-1">PNG, JPG, or WebP</span></div>}{compact&&items.length===0&&<button type="button" onClick={handleOpenPicker} disabled={disabled} className="text-xs font-semibold text-zinc-500 hover:text-amber-700 inline-flex items-center gap-1"><Plus className="w-3.5 h-3.5"/>Add portfolio image</button>}</div>{items.length===0&&!uploadingQueue.length&&!compact&&<div className="p-4 rounded-xl bg-zinc-50 border border-zinc-200/80 flex items-center gap-3 text-xs text-zinc-600"><ImageIcon className="w-5 h-5 text-zinc-400"/><p>Upload images of your past projects, case studies, or design samples.</p></div>}</div>;
};