-- Pi watermark branding
-- Table: public.app_branding
-- Column: pi_watermark_path
--
-- The app now accepts any of these values:
-- 1) NULL/empty -> bundled /pi-watermark.svg is used.
-- 2) /pi-watermark.svg -> bundled application asset.
-- 3) A Supabase Storage path in the w3c-assets bucket, e.g. branding/my-watermark.svg
-- 4) A complete public HTTPS URL, e.g. https://cdn.example.com/my-watermark.svg
--
-- To use the bundled watermark explicitly:
-- UPDATE public.app_branding
-- SET pi_watermark_path = '/pi-watermark.svg'
-- WHERE id = 'global';
--
-- To use a file uploaded to the w3c-assets bucket:
-- UPDATE public.app_branding
-- SET pi_watermark_path = 'branding/my-watermark.svg'
-- WHERE id = 'global';
--
-- To use an externally hosted public asset:
-- UPDATE public.app_branding
-- SET pi_watermark_path = 'https://example.com/my-watermark.svg'
-- WHERE id = 'global';
